/*
 *
 * Copyright C 2018, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 */
package com.spectralogic.s3.dataplanner.frontend;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

import org.apache.log4j.Logger;

import com.spectralogic.s3.common.dao.domain.ds3.DataIsolationLevel;
import com.spectralogic.s3.common.dao.domain.ds3.DataPersistenceRule;
import com.spectralogic.s3.common.dao.domain.ds3.DataPersistenceRuleType;
import com.spectralogic.s3.common.dao.domain.ds3.DataPlacementRuleState;
import com.spectralogic.s3.common.dao.domain.ds3.DataPolicy;
import com.spectralogic.s3.common.dao.domain.ds3.StorageDomain;
import com.spectralogic.s3.common.dao.domain.ds3.StorageDomainMember;
import com.spectralogic.s3.common.dao.domain.ds3.VersioningLevel;
import com.spectralogic.s3.common.dao.domain.ds3.WriteOptimization;
import com.spectralogic.s3.common.dao.domain.pool.Pool;
import com.spectralogic.s3.common.dao.domain.pool.PoolPartition;
import com.spectralogic.s3.common.dao.domain.pool.PoolType;
import com.spectralogic.s3.common.dao.domain.shared.NameObservable;
import com.spectralogic.s3.common.dao.domain.tape.Tape;
import com.spectralogic.s3.common.dao.domain.tape.TapePartition;
import com.spectralogic.s3.common.dao.domain.tape.TapePartitionState;
import com.spectralogic.s3.common.dao.domain.tape.TapeType;
import com.spectralogic.s3.common.dao.service.ds3.DataPolicyService;
import com.spectralogic.s3.common.dao.service.ds3.StorageDomainMemberService;
import com.spectralogic.s3.common.dao.service.ds3.StorageDomainService;
import com.spectralogic.s3.common.rpc.dataplanner.DataPolicyManagementResource;
import com.spectralogic.util.bean.BeanFactory;
import com.spectralogic.util.db.domain.service.KeyValueService;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.lang.CollectionFactory;
import com.spectralogic.util.lang.Validations;
import com.spectralogic.util.shutdown.BaseShutdownable;
import com.spectralogic.util.thread.RecurringRunnableExecutor;

/**
 * Generated default data policy dao definitions that meet most customer needs, based on whether a tape,
 * pool, or hybrid backend shows up.
 */
public final class DefaultDataPolicyGenerator extends BaseShutdownable
{
    public DefaultDataPolicyGenerator( 
            final DataPolicyManagementResource resource,
            final BeansServiceManager serviceManager,
            final int intervalInMillisToRun )
    {
        Validations.verifyNotNull( "Resource", resource );
        Validations.verifyNotNull( "Service manager", serviceManager );
        
        m_resource = resource;
        m_serviceManager = serviceManager;
        m_executor = new RecurringRunnableExecutor(
                m_worker, 
                intervalInMillisToRun );
        
        m_tape1 = new AutoCreateType( DATA_POLICY_TAPE_SINGLE_COPY_NAME );
        m_tape2 = new AutoCreateType( DATA_POLICY_TAPE_DUAL_COPY_NAME );
        m_tape3 = new AutoCreateType( DATA_POLICY_DB_BACKUP );
        m_pool = new AutoCreateType( DATA_POLICY_POOL_NAME );
        m_hybrid1 = new AutoCreateType( DATA_POLICY_HYBRID_SINGLE_COPY_NAME );
        m_hybrid2 = new AutoCreateType( DATA_POLICY_HYBRID_DUAL_COPY_NAME );
        
        m_executor.start();
        addShutdownListener( m_executor );
    }
    
    
    private final class AutoGeneratedPolicyCreator implements Runnable
    {
        public void run()
        {
            final int numTapePartitions = m_serviceManager.getRetriever( TapePartition.class ).getCount( 
                    Require.all( 
                            Require.beanPropertyEquals( TapePartition.STATE, TapePartitionState.ONLINE ),
                            Require.exists(
                                    Tape.class, 
                                    Tape.PARTITION_ID,
                                    Require.beanPropertyEqualsOneOf(
                                            Tape.TYPE,
                                            TapeType.getDataContainingTypes() ) ) ) );
            final int numPoolPartitions = m_serviceManager.getRetriever( PoolPartition.class ).getCount(
                    Require.all( 
                            Require.beanPropertyEquals( PoolPartition.TYPE, PoolType.NEARLINE ),
                            Require.exists( Pool.class, Pool.PARTITION_ID, Require.nothing() ) ) );
            if ( m_tape1.m_create && 0 < numTapePartitions )
            {
                generateTapePolicy();
            }
            if ( m_pool.m_create && 0 < numPoolPartitions )
            {
                generatePoolPolicy();
            }
            if ( m_hybrid1.m_create && 0 < numTapePartitions && 0 < numPoolPartitions )
            {
                generateHybridPolicy();
            }
            
            if ( m_tape1.m_create || m_pool.m_create || m_hybrid1.m_create )
            {
                return;
            }
            m_executor.shutdown();
        }
    } // end inner class def
    
    
    private void generateTapePolicy()
    {
        m_tape1.startedCreating();
        m_tape2.startedCreating();
        m_tape3.startedCreating();
        
        final StorageDomain sd1 = BeanFactory.newBean( StorageDomain.class )
                .setName( STORAGE_DOMAIN_TAPE_SINGLE_COPY_NAME );
        m_serviceManager.getService( StorageDomainService.class ).create( sd1 );
        
        final StorageDomain sd2 = BeanFactory.newBean( StorageDomain.class )
                .setName( STORAGE_DOMAIN_TAPE_DUAL_COPY_NAME );
        m_serviceManager.getService( StorageDomainService.class ).create( sd2 );
        
        final StorageDomain sd3 = BeanFactory.newBean( StorageDomain.class )
                .setName( STORAGE_DOMAIN_BACKUP_SINGLE_COPY_NAME )
                .setSecureMediaAllocation( false );
        m_serviceManager.getService( StorageDomainService.class ).create( sd3 );
        
        final StorageDomain sd4 = BeanFactory.newBean( StorageDomain.class )
                .setName( STORAGE_DOMAIN_BACKUP_DUAL_COPY_NAME )
                .setSecureMediaAllocation( false );
        m_serviceManager.getService( StorageDomainService.class ).create( sd4 );
        
        final Map< UUID, Set< TapeType > > members = new HashMap<>();
        for ( final Tape tape : m_serviceManager.getRetriever( Tape.class )
                                                .retrieveAll( Require.not(
                                                        Require.beanPropertyEquals( Tape.TYPE, TapeType.UNKNOWN ) ) )
                                                .toSet() )
        {
            if ( !members.containsKey( tape.getPartitionId() ) )
            {
                members.put( tape.getPartitionId(), new HashSet<>() );
            }
            
            final Set< TapeType > tapeTypes = members.get( tape.getPartitionId() );
            if ( tapeTypes.contains( tape.getType() ) || !tape.getType().canContainData() )
            {
                continue;
            }
    
            TapePartition tp = m_serviceManager.getRetriever( TapePartition.class )
                                               .attain( TapePartition.ID, tape.getPartitionId() );
            if ( tp.getDriveType()
                   .isWriteSupported( tape.getType() ) )
            {
                tapeTypes.add( tape.getType() );
                for ( final UUID storageDomainId : CollectionFactory.toSet( sd1.getId(), sd2.getId(), sd3.getId(),
                        sd4.getId() ) )
                {
                    m_serviceManager.getService( StorageDomainMemberService.class ).create( BeanFactory.newBean( StorageDomainMember.class )
                                                                                                       .setStorageDomainId( storageDomainId ).setTapePartitionId( tape.getPartitionId() )
                                                                                                       .setTapeType( tape.getType() ) );
                }
            }
        }
        
        synchronized ( m_resource )
        {
            final DataPolicy policy1 = m_tape1.create();
            m_resource.createDataPersistenceRule( BeanFactory.newBean( DataPersistenceRule.class )
                    .setDataPolicyId( policy1.getId() )
                    .setState( DataPlacementRuleState.NORMAL )
                    .setType( DataPersistenceRuleType.PERMANENT )
                    .setIsolationLevel( DataIsolationLevel.BUCKET_ISOLATED )
                    .setStorageDomainId( sd1.getId() ) );

            final DataPolicy policy2 = m_tape2.create();
            m_resource.createDataPersistenceRule( BeanFactory.newBean( DataPersistenceRule.class )
                    .setDataPolicyId( policy2.getId() )
                    .setState( DataPlacementRuleState.NORMAL )
                    .setType( DataPersistenceRuleType.PERMANENT )
                    .setIsolationLevel( DataIsolationLevel.BUCKET_ISOLATED )
                    .setStorageDomainId( sd1.getId() ) );
            m_resource.createDataPersistenceRule( BeanFactory.newBean( DataPersistenceRule.class )
                    .setDataPolicyId( policy2.getId() )
                    .setState( DataPlacementRuleState.NORMAL )
                    .setType( DataPersistenceRuleType.PERMANENT )
                    .setIsolationLevel( DataIsolationLevel.BUCKET_ISOLATED )
                    .setStorageDomainId( sd2.getId() ) );

            final DataPolicy policy3 = m_tape3.create();
            m_resource.createDataPersistenceRule( BeanFactory.newBean( DataPersistenceRule.class )
                    .setDataPolicyId( policy3.getId() )
                    .setState( DataPlacementRuleState.NORMAL )
                    .setType( DataPersistenceRuleType.PERMANENT )
                    .setIsolationLevel( DataIsolationLevel.BUCKET_ISOLATED )
                    .setStorageDomainId( sd3.getId() ) );
            m_resource.createDataPersistenceRule( BeanFactory.newBean( DataPersistenceRule.class )
                    .setDataPolicyId( policy3.getId() )
                    .setState( DataPlacementRuleState.NORMAL )
                    .setType( DataPersistenceRuleType.PERMANENT )
                    .setIsolationLevel( DataIsolationLevel.BUCKET_ISOLATED )
                    .setStorageDomainId( sd4.getId() ) );
        }
    }
    
    
    private void generatePoolPolicy()
    {
        m_pool.startedCreating();
        
        final StorageDomain sd1 = BeanFactory.newBean( StorageDomain.class )
                .setName( STORAGE_DOMAIN_POOL_NAME ).setWriteOptimization( WriteOptimization.PERFORMANCE );
        m_serviceManager.getService( StorageDomainService.class ).create( sd1 );
        
        for ( final PoolPartition partition 
                : m_serviceManager.getRetriever( PoolPartition.class ).retrieveAll(
                        PoolPartition.TYPE, PoolType.NEARLINE ).toSet() )
        {
            m_serviceManager.getService( StorageDomainMemberService.class ).create( 
                    BeanFactory.newBean( StorageDomainMember.class )
                    .setStorageDomainId( sd1.getId() ).setPoolPartitionId( partition.getId() ) );
        }
        
        synchronized ( m_resource )
        {
            final DataPolicy policy = m_pool.create();
            m_resource.createDataPersistenceRule( BeanFactory.newBean( DataPersistenceRule.class )
                    .setDataPolicyId( policy.getId() )
                    .setState( DataPlacementRuleState.NORMAL )
                    .setType( DataPersistenceRuleType.PERMANENT )
                    .setIsolationLevel( DataIsolationLevel.STANDARD )
                    .setStorageDomainId( sd1.getId() ) );
        }
    }
    
    
    private void generateHybridPolicy()
    {
        synchronized ( m_resource )
        {
            final StorageDomain tapeStorageDomain1 = 
                    m_serviceManager.getRetriever( StorageDomain.class ).retrieve(
                            NameObservable.NAME, STORAGE_DOMAIN_TAPE_SINGLE_COPY_NAME );
            final StorageDomain tapeStorageDomain2 = 
                    m_serviceManager.getRetriever( StorageDomain.class ).retrieve(
                            NameObservable.NAME, STORAGE_DOMAIN_TAPE_DUAL_COPY_NAME );
            final StorageDomain poolStorageDomain = 
                    m_serviceManager.getRetriever( StorageDomain.class ).retrieve(
                            NameObservable.NAME, STORAGE_DOMAIN_POOL_NAME );
            if ( null == tapeStorageDomain1 )
            {
                LOG.warn( "Unable to auto-generate hybrid data policy since storage domain \""
                        + STORAGE_DOMAIN_TAPE_SINGLE_COPY_NAME + "\" does not exist.");
                LOG.info( "Default storage domain " + STORAGE_DOMAIN_TAPE_SINGLE_COPY_NAME + " has been renamed. So wont try this again.");
                m_hybrid1.m_create = false;
                return;
            }
            else if ( null == tapeStorageDomain2 )
            {
                LOG.warn( "Unable to auto-generate hybrid data policy since storage domain \""
                        + STORAGE_DOMAIN_TAPE_DUAL_COPY_NAME + "\" does not exist.");
                LOG.info( "Default storage domain " + STORAGE_DOMAIN_TAPE_DUAL_COPY_NAME + " has been renamed. So wont try this again.");
                m_hybrid2.m_create = false;
                return;
            }
            else if ( null == poolStorageDomain )
            {
                LOG.warn( "Unable to auto-generate hybrid data policy since storage domain \""
                        + STORAGE_DOMAIN_POOL_NAME + "\" does not exist.");
                LOG.info( "Default storage domain " + STORAGE_DOMAIN_POOL_NAME + " has been renamed. So wont try this again.");
                m_pool.m_create = false;
                return;
            }
            
            final DataPolicy policy1 = m_hybrid1.create();
            m_resource.createDataPersistenceRule( BeanFactory.newBean( DataPersistenceRule.class )
                    .setDataPolicyId( policy1.getId() )
                    .setState( DataPlacementRuleState.NORMAL )
                    .setType( DataPersistenceRuleType.PERMANENT )
                    .setIsolationLevel( DataIsolationLevel.BUCKET_ISOLATED )
                    .setStorageDomainId( tapeStorageDomain1.getId() ) );
            m_resource.createDataPersistenceRule( BeanFactory.newBean( DataPersistenceRule.class )
                    .setDataPolicyId( policy1.getId() )
                    .setState( DataPlacementRuleState.NORMAL )
                    .setType( DataPersistenceRuleType.PERMANENT )
                    .setIsolationLevel( DataIsolationLevel.STANDARD )
                    .setStorageDomainId( poolStorageDomain.getId() ) );
            
            final DataPolicy policy2 = m_hybrid2.create();
            m_resource.createDataPersistenceRule( BeanFactory.newBean( DataPersistenceRule.class )
                    .setDataPolicyId( policy2.getId() )
                    .setState( DataPlacementRuleState.NORMAL )
                    .setType( DataPersistenceRuleType.PERMANENT )
                    .setIsolationLevel( DataIsolationLevel.BUCKET_ISOLATED )
                    .setStorageDomainId( tapeStorageDomain1.getId() ) );
            m_resource.createDataPersistenceRule( BeanFactory.newBean( DataPersistenceRule.class )
                    .setDataPolicyId( policy2.getId() )
                    .setState( DataPlacementRuleState.NORMAL )
                    .setType( DataPersistenceRuleType.PERMANENT )
                    .setIsolationLevel( DataIsolationLevel.BUCKET_ISOLATED )
                    .setStorageDomainId( tapeStorageDomain2.getId() ) );
            m_resource.createDataPersistenceRule( BeanFactory.newBean( DataPersistenceRule.class )
                    .setDataPolicyId( policy2.getId() )
                    .setState( DataPlacementRuleState.NORMAL )
                    .setType( DataPersistenceRuleType.PERMANENT )
                    .setIsolationLevel( DataIsolationLevel.STANDARD )
                    .setStorageDomainId( poolStorageDomain.getId() ) );
        }
    }
    
    
    private final class AutoCreateType
    {
        private AutoCreateType( final String name )
        {
            m_name = name;
            m_key = "AutoGeneratedDataPolicy-" + name;
            if ( null != m_serviceManager.getRetriever( DataPolicy.class ).retrieve(
                    NameObservable.NAME, name ) )
            {
                m_create = false;
            }
            else
                m_create = !m_serviceManager.getService( KeyValueService.class )
                                            .getBoolean( m_key, false );
        }
        
        private void startedCreating()
        {
            m_create = false;
            m_serviceManager.getService( KeyValueService.class ).set( m_key, true );
        }
        
        private DataPolicy create()
        {
            startedCreating();
            final DataPolicy dataPolicy = BeanFactory.newBean( DataPolicy.class ).setName( m_name );
            if ( DATA_POLICY_DB_BACKUP.equals( m_name ) )
            {
                dataPolicy.setAlwaysForcePutJobCreation( true );
                dataPolicy.setBlobbingEnabled( false );
                // EMPROD-1812
                dataPolicy.setVersioning( VersioningLevel.NONE );
            }
            m_serviceManager.getService( DataPolicyService.class ).create( dataPolicy );
            return dataPolicy;
        }
        
        private boolean m_create;
        private final String m_name;
        private final String m_key;
    } // end inner class def

    
    private final AutoCreateType m_tape1;
    private final AutoCreateType m_tape2;
    private final AutoCreateType m_tape3;
    private final AutoCreateType m_pool;
    private final AutoCreateType m_hybrid1;
    private final AutoCreateType m_hybrid2;
    
    private final AutoGeneratedPolicyCreator m_worker =
            new AutoGeneratedPolicyCreator();
    private final RecurringRunnableExecutor m_executor;
    private final DataPolicyManagementResource m_resource;
    private final BeansServiceManager m_serviceManager;

    final static String DATA_POLICY_DB_BACKUP = "Database Backup";
    final static String DATA_POLICY_TAPE_SINGLE_COPY_NAME = "Single Copy on Tape";
    final static String DATA_POLICY_TAPE_DUAL_COPY_NAME = "Dual Copy on Tape";
    final static String DATA_POLICY_POOL_NAME = "Single Copy on Nearline Disk";
    final static String DATA_POLICY_HYBRID_SINGLE_COPY_NAME = "Single Copy on Nearline Disk and Tape";
    final static String DATA_POLICY_HYBRID_DUAL_COPY_NAME =
            "Single Copy on Nearline Disk and Dual Copy on Tape";
    final static String STORAGE_DOMAIN_TAPE_SINGLE_COPY_NAME = "Tape First Copy";
    final static String STORAGE_DOMAIN_TAPE_DUAL_COPY_NAME = "Tape Second Copy";
    final static String STORAGE_DOMAIN_BACKUP_SINGLE_COPY_NAME = "Db Backup First Copy";
    final static String STORAGE_DOMAIN_BACKUP_DUAL_COPY_NAME = "Db Backup Second Copy";
    final static String STORAGE_DOMAIN_POOL_NAME = "Pool First Copy";
    final static Logger LOG = Logger.getLogger( DefaultDataPolicyGenerator.class );
}
