/*******************************************************************************
 *
 * Copyright C 2014, Spectra Logic Corporation and/or its affiliates.  
 * All rights reserved.
 *
 ******************************************************************************/
package com.spectralogic.s3.common.rpc.tape.domain;

import com.spectralogic.s3.common.dao.domain.shared.ElementAddressObservable;
import com.spectralogic.s3.common.dao.domain.shared.ErrorMessageObservable;
import com.spectralogic.s3.common.dao.domain.shared.SerialNumberObservable;
import com.spectralogic.s3.common.dao.domain.tape.TapeDriveType;
import com.spectralogic.s3.common.rpc.tape.TapeDriveResource;
import com.spectralogic.util.bean.lang.Optional;
import com.spectralogic.util.bean.lang.SimpleBeanSafeToProxy;

/**
 * Note: There are 2 serial numbers you can get for a tape drive.  One is manufacturer-supplied and is
 * immutable.  The other is generated by Spectra and will change depending on the frame location and element
 * address of the tape drive.  The serial number to be reported when dealing with tape drives shall always
 * be the manufacturer-supplied one.
 */
public interface TapeDriveInformation
  extends SimpleBeanSafeToProxy, SerialNumberObservable< TapeDriveInformation >, 
          ErrorMessageObservable< TapeDriveInformation >,
          ElementAddressObservable< TapeDriveInformation >
{
    String TYPE = "type";
    
    TapeDriveType getType();
    
    TapeDriveInformation setType( final TapeDriveType value );
    
    
    String FORCE_TAPE_REMOVAL = "forceTapeRemoval";
    
    /**
     * @return TRUE if the tape drive requires that the tape in it be moved out at the earliest opportunity
     * <br><br>
     * A tape drive may report that a forced tape removal is required if:
     * <ol>
     * <li> The tape does not have a bar code and must be moved to storage to determine its bar code
     * <li> A hardware malfunction has occurred and the tape must be moved away to attempt to correct the 
     * issue
     * </ol>
     * 
     * Note: If this flag is set, a {@link TapeDriveResource#prepareForRemoval} call may not succeed, and if
     * it does not succeed, this should not prevent the tape from being moved.
     */
    @Optional
    Boolean getForceTapeRemoval();
    
    void setForceTapeRemoval( final Boolean value );
    
    
    String CLEANING_REQUIRED = "cleaningRequired";
    
    /**
     * @return TRUE if the tape drive requires cleaning at the earliest opportunity
     */
    @Optional
    Boolean getCleaningRequired();
    
    void setCleaningRequired( final Boolean value );
    
    
    String MFG_SERIAL_NUMBER = "mfgSerialNumber";
    
    @Optional
    String getMfgSerialNumber();
    
    TapeDriveInformation setMfgSerialNumber( final String value );


    String CHARACTERIZATION_VER = "characterizationVer";

    String getCharacterizationVer();

    TapeDriveInformation setCharacterizationVer( final String value );


}
