# Use official Tomcat base image
FROM tomcat:9.0

# Update package lists and install vim
RUN apt-get update && apt-get install -y vim file
RUN apt-get update && apt-get install -y ntpdate

# Set the working directory inside the container
WORKDIR /usr/local/tomcat/webapps/

COPY docker/tapesystem.properties /etc/spectralogic/
# Copy the .war file into Tomcat's webapps directory
COPY server/build/libs/server-0.0.4-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war
COPY DataPlanner/src/test/resources/etc/spectra/pf-s3port.conf /etc/spectra/
COPY DataPlanner/src/test/resources/etc/spectra/serial_number /etc/spectra/
COPY server/src/main/resources/log4j.xml /usr/local/tomcat/conf/log4j.xml
COPY docker/version.server.conf /etc/version.conf

COPY docker/entrypoint-time-sync.sh /usr/local/bin/entrypoint-time-sync.sh
RUN chmod +x /usr/local/bin/entrypoint-time-sync.sh

# To bypass authentication
RUN touch /usr/local/tomcat/temp/_FLAG_disablerequesthandlerauthentication 

RUN mkdir -p /var/log/tomcat &&chown -R 1000:1000 /var/log/tomcat
# Expose Tomcat port
EXPOSE 8080


ENV CATALINA_OPTS="-Dlog4j.configuration=file:/usr/local/tomcat/conf/log4j.xml -Dlog4j.debug=true"
# Start Tomcat
#CMD ["catalina.sh", "run", "-Dlog4j.configuration=file:/usr/local/tomcat/conf/log4j.xml","-Dlog4j.debug=true"]
ENTRYPOINT ["/usr/local/bin/entrypoint-time-sync.sh", "catalina.sh", "run"]

