#################################
#  Java tape frontend properities
#
# Variables delimied with $$, ie $$NAME, are updated by the RPM deploy

# common settings
com.spectralogic.em.sitename=disknode1site
com.spectralogic.em.complexname=disknode1complex
com.spectralogic.em.logroot=/var/log
com.spectralogic.em.nodeid=b6b8973a-4bc5-11e3-b95f-002590958758
com.spectralogic.em.backend.monitorport=56000

# dataplanner specific settings
com.spectralogic.em.cachemanager.cachedir=/usr/local/bluestorm/frontend/cachedir
#com.spectralogic.em.cachemanager.cachesize=300000000
com.spectralogic.em.dataplanner.monitorport=8081
com.spectralogic.em.frontend.tmpdir=/tmp
com.spectralogic.em.virtualcache.pagesize=52428800

# S3 front3end specific settings
com.spectralogic.em.frontend.authorizationmode=strict
com.spectralogic.em.frontend.pathonly=false
com.spectralogic.em.frontend.port=8080

# JiveResource settings
com.spectralogic.em.jiveresource.driver=org.postgresql.Driver
com.spectralogic.em.jiveresource.url=jdbc:postgresql://postgresreplica/tapesystem?autoReconnect=true
com.spectralogic.em.jiveresource.host=postgresreplica
com.spectralogic.em.jiveresource.schema=tapesystem
com.spectralogic.em.jiveresource.username=Administrator
com.spectralogic.em.jiveresource.password=dogfish

# backend
com.spectralogic.em.tapebackend.changerresourceclass=tapechanger
com.spectralogic.em.tapebackend.changerresourceinstance=tapechangerinstance
com.spectralogic.em.tapebackend.moverresourceclass=datamover

com.spectralogic.em.tapechanger.scsi=/dev/ch0
com.spectralogic.em.tapechanger.autoformat=true
com.spectralogic.em.tapechanger.defaultimportuser=
