/*******************************************************************************
 *
 * Copyright C 2013, Spectra Logic Corporation and/or its affiliates.  
 * All rights reserved.
 *
 ******************************************************************************/
package com.spectralogic.util.bean.lang;

import java.lang.annotation.*;

/**
 * Annotate bean getter methods that can are generated by postgres, request/response payloads, etc. with this
 * annotation.  Various infrastructure components may use this annotation to validate that required fields
 * are populated. Properties are required by default and require this annotation to be managed by the database.
 * This annotation should only be used with auto-incrementing numbers such as SERIAL and BIGSERIAL.
 * <br><br>
 */
@Documented
@Retention( RetentionPolicy.RUNTIME )
@Target( ElementType.METHOD )
public @interface AutoIncrementing
{
    // empty
}
