/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.AzureDataReplicationRule;
import com.spectralogic.s3.common.dao.domain.ds3.DataPlacement;
import com.spectralogic.s3.common.dao.domain.ds3.DataPlacementRuleState;
import com.spectralogic.s3.common.dao.domain.ds3.DataReplicationRule;
import com.spectralogic.s3.common.dao.domain.ds3.DataReplicationRuleType;
import com.spectralogic.s3.common.dao.domain.ds3.DegradedBlob;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import java.util.UUID;


public class AzureDataReplicationRuleRM
{
    public AzureDataReplicationRuleRM( AzureDataReplicationRule bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public AzureDataReplicationRuleRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    AzureDataReplicationRuleRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


   synchronized public RetrieveBeansResult< DegradedBlob > getDegradedBlobs()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DegradedBlob.class ).retrieveAll(
            Require.beanPropertyEquals( DegradedBlob.AZURE_REPLICATION_RULE_ID, m_bean.getId() ) );
    }


    synchronized public DataPolicyRM getDataPolicy()
    {
        if ( null != m_bean )
        {
            return new DataPolicyRM( m_bean.getDataPolicyId(), m_serviceManager );
        }
        return new DataPolicyRM(
                Require.exists( AzureDataReplicationRule.class,
                        DataPlacement.DATA_POLICY_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public long getMaxBlobPartSizeInBytes()
    {
        fetchBeanIfNull();
        return  m_bean.getMaxBlobPartSizeInBytes();
    }


    synchronized public boolean isReplicateDeletes()
    {
        fetchBeanIfNull();
        return  m_bean.isReplicateDeletes();
    }


    synchronized public DataPlacementRuleState getState()
    {
        fetchBeanIfNull();
        return  m_bean.getState();
    }


    synchronized public AzureTargetRM getTarget()
    {
        if ( null != m_bean )
        {
            return new AzureTargetRM( m_bean.getTargetId(), m_serviceManager );
        }
        return new AzureTargetRM(
                Require.exists( AzureDataReplicationRule.class,
                        DataReplicationRule.TARGET_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public DataReplicationRuleType getType()
    {
        fetchBeanIfNull();
        return  m_bean.getType();
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( AzureDataReplicationRule.class ).attain( m_whereClause );
        }
    }


    synchronized public AzureDataReplicationRule unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private AzureDataReplicationRule m_bean;
}
