/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.AzureBlobDestination;
import com.spectralogic.s3.common.dao.domain.ds3.AzureDataReplicationRule;
import com.spectralogic.s3.common.dao.domain.ds3.CloudNamingMode;
import com.spectralogic.s3.common.dao.domain.ds3.DataReplicationRule;
import com.spectralogic.s3.common.dao.domain.ds3.DetailedAzureBlobDestination;
import com.spectralogic.s3.common.dao.domain.ds3.DetailedJobEntry;
import com.spectralogic.s3.common.dao.domain.ds3.JobEntry;
import com.spectralogic.s3.common.dao.domain.ds3.RemoteBlobDestination;
import com.spectralogic.s3.common.dao.domain.shared.ImportPublicCloudTargetDirective;
import com.spectralogic.s3.common.dao.domain.shared.Quiesced;
import com.spectralogic.s3.common.dao.domain.shared.ReadFromObservable;
import com.spectralogic.s3.common.dao.domain.target.AzureTarget;
import com.spectralogic.s3.common.dao.domain.target.AzureTargetBucketName;
import com.spectralogic.s3.common.dao.domain.target.AzureTargetFailure;
import com.spectralogic.s3.common.dao.domain.target.AzureTargetReadPreference;
import com.spectralogic.s3.common.dao.domain.target.BlobAzureTarget;
import com.spectralogic.s3.common.dao.domain.target.BlobTarget;
import com.spectralogic.s3.common.dao.domain.target.ImportAzureTargetDirective;
import com.spectralogic.s3.common.dao.domain.target.PublicCloudTargetBucketName;
import com.spectralogic.s3.common.dao.domain.target.SuspectBlobAzureTarget;
import com.spectralogic.s3.common.dao.domain.target.TargetFailure;
import com.spectralogic.s3.common.dao.domain.target.TargetReadPreference;
import com.spectralogic.s3.common.dao.domain.target.TargetReadPreferenceType;
import com.spectralogic.s3.common.dao.domain.target.TargetState;
import com.spectralogic.s3.common.dao.domain.temp.BlobAzureTargetToVerify;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import java.util.Date;
import java.util.UUID;


public class AzureTargetRM
{
    public AzureTargetRM( AzureTarget bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public AzureTargetRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    AzureTargetRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public String getAccountKey()
    {
        fetchBeanIfNull();
        return  m_bean.getAccountKey();
    }


    synchronized public String getAccountName()
    {
        fetchBeanIfNull();
        return  m_bean.getAccountName();
    }


    synchronized public Integer getAutoVerifyFrequencyInDays()
    {
        fetchBeanIfNull();
        return  m_bean.getAutoVerifyFrequencyInDays();
    }


    synchronized public String getCloudBucketPrefix()
    {
        fetchBeanIfNull();
        return  m_bean.getCloudBucketPrefix();
    }


    synchronized public String getCloudBucketSuffix()
    {
        fetchBeanIfNull();
        return  m_bean.getCloudBucketSuffix();
    }


    synchronized public TargetReadPreferenceType getDefaultReadPreference()
    {
        fetchBeanIfNull();
        return  m_bean.getDefaultReadPreference();
    }


    synchronized public boolean isHttps()
    {
        fetchBeanIfNull();
        return  m_bean.isHttps();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public Date getLastFullyVerified()
    {
        fetchBeanIfNull();
        return  m_bean.getLastFullyVerified();
    }


    synchronized public String getName()
    {
        fetchBeanIfNull();
        return  m_bean.getName();
    }


    synchronized public CloudNamingMode getNamingMode()
    {
        fetchBeanIfNull();
        return  m_bean.getNamingMode();
    }


    synchronized public boolean isPermitGoingOutOfSync()
    {
        fetchBeanIfNull();
        return  m_bean.isPermitGoingOutOfSync();
    }


    synchronized public Quiesced getQuiesced()
    {
        fetchBeanIfNull();
        return  m_bean.getQuiesced();
    }


   synchronized public RetrieveBeansResult< DetailedJobEntry > getDetailedJobEntries()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DetailedJobEntry.class ).retrieveAll(
            Require.beanPropertyEquals( ReadFromObservable.READ_FROM_AZURE_TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< JobEntry > getJobEntries()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( JobEntry.class ).retrieveAll(
            Require.beanPropertyEquals( ReadFromObservable.READ_FROM_AZURE_TARGET_ID, m_bean.getId() ) );
    }


    synchronized public TargetState getState()
    {
        fetchBeanIfNull();
        return  m_bean.getState();
    }


   synchronized public RetrieveBeansResult< DetailedAzureBlobDestination > getDetailedAzureBlobDestinations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DetailedAzureBlobDestination.class ).retrieveAll(
            Require.beanPropertyEquals( RemoteBlobDestination.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BlobAzureTarget > getBlobAzureTargets()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BlobAzureTarget.class ).retrieveAll(
            Require.beanPropertyEquals( BlobTarget.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< AzureTargetReadPreference > getAzureTargetReadPreferences()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( AzureTargetReadPreference.class ).retrieveAll(
            Require.beanPropertyEquals( TargetReadPreference.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< AzureBlobDestination > getAzureBlobDestinations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( AzureBlobDestination.class ).retrieveAll(
            Require.beanPropertyEquals( RemoteBlobDestination.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< ImportAzureTargetDirective > getImportAzureTargetDirectives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ImportAzureTargetDirective.class ).retrieveAll(
            Require.beanPropertyEquals( ImportPublicCloudTargetDirective.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< AzureTargetFailure > getAzureTargetFailures()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( AzureTargetFailure.class ).retrieveAll(
            Require.beanPropertyEquals( TargetFailure.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< AzureDataReplicationRule > getAzureDataReplicationRules()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( AzureDataReplicationRule.class ).retrieveAll(
            Require.beanPropertyEquals( DataReplicationRule.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< AzureTargetBucketName > getAzureTargetBucketNames()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( AzureTargetBucketName.class ).retrieveAll(
            Require.beanPropertyEquals( PublicCloudTargetBucketName.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< SuspectBlobAzureTarget > getSuspectBlobAzureTargets()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( SuspectBlobAzureTarget.class ).retrieveAll(
            Require.beanPropertyEquals( BlobTarget.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BlobAzureTargetToVerify > getBlobAzureTargetToVerifies()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BlobAzureTargetToVerify.class ).retrieveAll(
            Require.beanPropertyEquals( BlobTarget.TARGET_ID, m_bean.getId() ) );
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( AzureTarget.class ).attain( m_whereClause );
        }
    }


    synchronized public AzureTarget unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private AzureTarget m_bean;
}
