/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.planner.BlobCache;
import com.spectralogic.s3.common.dao.domain.planner.CacheEntryState;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import java.util.Date;
import java.util.UUID;


public class BlobCacheRM
{
    public BlobCacheRM( BlobCache bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public BlobCacheRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    BlobCacheRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public BlobRM getBlob()
    {
        if ( null != m_bean )
        {
            return new BlobRM( m_bean.getBlobId(), m_serviceManager );
        }
        return new BlobRM(
                Require.exists( BlobCache.class,
                        BlobCache.BLOB_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public Date getLastAccessed()
    {
        fetchBeanIfNull();
        return  m_bean.getLastAccessed();
    }


    synchronized public String getPath()
    {
        fetchBeanIfNull();
        return  m_bean.getPath();
    }


    synchronized public long getSizeInBytes()
    {
        fetchBeanIfNull();
        return  m_bean.getSizeInBytes();
    }


    synchronized public CacheEntryState getState()
    {
        fetchBeanIfNull();
        return  m_bean.getState();
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( BlobCache.class ).attain( m_whereClause );
        }
    }


    synchronized public BlobCache unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private BlobCache m_bean;
}
