/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.pool.BlobPool;
import com.spectralogic.s3.common.dao.domain.pool.ObsoleteBlobPool;
import com.spectralogic.s3.common.dao.domain.pool.SuspectBlobPool;
import com.spectralogic.s3.common.dao.domain.shared.BlobObservable;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import java.util.Date;
import java.util.UUID;


public class BlobPoolRM
{
    public BlobPoolRM( BlobPool bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public BlobPoolRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    BlobPoolRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public BlobRM getBlob()
    {
        if ( null != m_bean )
        {
            return new BlobRM( m_bean.getBlobId(), m_serviceManager );
        }
        return new BlobRM(
                Require.exists( BlobPool.class,
                        BlobObservable.BLOB_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public BucketRM getBucket()
    {
        if ( null != m_bean )
        {
            return new BucketRM( m_bean.getBucketId(), m_serviceManager );
        }
        return new BucketRM(
                Require.exists( BlobPool.class,
                        BlobPool.BUCKET_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public Date getDateWritten()
    {
        fetchBeanIfNull();
        return  m_bean.getDateWritten();
    }


   synchronized public RetrieveBeansResult< ObsoleteBlobPool > getObsoleteBlobPools()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ObsoleteBlobPool.class ).retrieveAll(
            Require.beanPropertyEquals( Identifiable.ID, m_bean.getId() ) );
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


   synchronized public RetrieveBeansResult< SuspectBlobPool > getSuspectBlobPools()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( SuspectBlobPool.class ).retrieveAll(
            Require.beanPropertyEquals( Identifiable.ID, m_bean.getId() ) );
    }


    synchronized public Date getLastAccessed()
    {
        fetchBeanIfNull();
        return  m_bean.getLastAccessed();
    }


    synchronized public PoolRM getPool()
    {
        if ( null != m_bean )
        {
            return new PoolRM( m_bean.getPoolId(), m_serviceManager );
        }
        return new PoolRM(
                Require.exists( BlobPool.class,
                        BlobPool.POOL_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( BlobPool.class ).attain( m_whereClause );
        }
    }


    synchronized public BlobPool unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private BlobPool m_bean;
}
