/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.LocalBlobDestination;
import com.spectralogic.s3.common.dao.domain.ds3.JobChunkBlobStoreState;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;

import java.util.UUID;


public class BlobLocalDestinationRM
{
    public BlobLocalDestinationRM(LocalBlobDestination bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public BlobLocalDestinationRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    BlobLocalDestinationRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public JobEntryRM getJobEntry()
    {
        if ( null != m_bean )
        {
            return new JobEntryRM( m_bean.getEntryId(), m_serviceManager );
        }
        return new JobEntryRM(
                Require.exists( LocalBlobDestination.class,
                        LocalBlobDestination.ENTRY_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public boolean isDone()
    {
        fetchBeanIfNull();
        return m_bean.getBlobStoreState() == JobChunkBlobStoreState.COMPLETED;
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public DataPersistenceRuleRM getPersistenceRule()
    {
        if ( null != m_bean )
        {
            return new DataPersistenceRuleRM( m_bean.getPersistenceRuleId(), m_serviceManager );
        }
        return new DataPersistenceRuleRM(
                Require.exists( LocalBlobDestination.class,
                        LocalBlobDestination.PERSISTENCE_RULE_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public StorageDomainRM getStorageDomain()
    {
        if ( null != m_bean )
        {
            return new StorageDomainRM( m_bean.getStorageDomainId(), m_serviceManager );
        }
        return new StorageDomainRM(
                Require.exists( LocalBlobDestination.class,
                        LocalBlobDestination.STORAGE_DOMAIN_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( LocalBlobDestination.class ).attain( m_whereClause );
        }
    }


    synchronized public LocalBlobDestination unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private LocalBlobDestination m_bean;
}
