/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.Blob;
import com.spectralogic.s3.common.dao.domain.ds3.DegradedBlob;
import com.spectralogic.s3.common.dao.domain.ds3.DetailedJobEntry;
import com.spectralogic.s3.common.dao.domain.ds3.JobEntry;
import com.spectralogic.s3.common.dao.domain.planner.BlobCache;
import com.spectralogic.s3.common.dao.domain.pool.BlobPool;
import com.spectralogic.s3.common.dao.domain.pool.ObsoleteBlobPool;
import com.spectralogic.s3.common.dao.domain.pool.SuspectBlobPool;
import com.spectralogic.s3.common.dao.domain.shared.BlobObservable;
import com.spectralogic.s3.common.dao.domain.tape.BlobTape;
import com.spectralogic.s3.common.dao.domain.tape.ObsoleteBlobTape;
import com.spectralogic.s3.common.dao.domain.tape.SuspectBlobTape;
import com.spectralogic.s3.common.dao.domain.target.BlobAzureTarget;
import com.spectralogic.s3.common.dao.domain.target.BlobDs3Target;
import com.spectralogic.s3.common.dao.domain.target.BlobS3Target;
import com.spectralogic.s3.common.dao.domain.target.SuspectBlobAzureTarget;
import com.spectralogic.s3.common.dao.domain.target.SuspectBlobDs3Target;
import com.spectralogic.s3.common.dao.domain.target.SuspectBlobS3Target;
import com.spectralogic.s3.common.dao.domain.temp.BlobAzureTargetToVerify;
import com.spectralogic.s3.common.dao.domain.temp.BlobS3TargetToVerify;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import com.spectralogic.util.security.ChecksumType;
import java.util.UUID;


public class BlobRM
{
    public BlobRM( Blob bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public BlobRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    BlobRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


   synchronized public RetrieveBeansResult< DetailedJobEntry > getDetailedJobEntries()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DetailedJobEntry.class ).retrieveAll(
            Require.beanPropertyEquals( BlobObservable.BLOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< JobEntry > getJobEntries()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( JobEntry.class ).retrieveAll(
            Require.beanPropertyEquals( BlobObservable.BLOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BlobDs3Target > getBlobDs3Targets()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BlobDs3Target.class ).retrieveAll(
            Require.beanPropertyEquals( BlobObservable.BLOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BlobAzureTarget > getBlobAzureTargets()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BlobAzureTarget.class ).retrieveAll(
            Require.beanPropertyEquals( BlobObservable.BLOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BlobS3Target > getBlobS3Targets()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BlobS3Target.class ).retrieveAll(
            Require.beanPropertyEquals( BlobObservable.BLOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< DegradedBlob > getDegradedBlobs()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DegradedBlob.class ).retrieveAll(
            Require.beanPropertyEquals( BlobObservable.BLOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BlobCache > getBlobCaches()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BlobCache.class ).retrieveAll(
            Require.beanPropertyEquals( BlobCache.BLOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< SuspectBlobDs3Target > getSuspectBlobDs3Targets()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( SuspectBlobDs3Target.class ).retrieveAll(
            Require.beanPropertyEquals( BlobObservable.BLOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< ObsoleteBlobTape > getObsoleteBlobTapes()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ObsoleteBlobTape.class ).retrieveAll(
            Require.beanPropertyEquals( BlobObservable.BLOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BlobTape > getBlobTapes()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BlobTape.class ).retrieveAll(
            Require.beanPropertyEquals( BlobObservable.BLOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BlobPool > getBlobPools()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BlobPool.class ).retrieveAll(
            Require.beanPropertyEquals( BlobObservable.BLOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< SuspectBlobPool > getSuspectBlobPools()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( SuspectBlobPool.class ).retrieveAll(
            Require.beanPropertyEquals( BlobObservable.BLOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< SuspectBlobS3Target > getSuspectBlobS3Targets()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( SuspectBlobS3Target.class ).retrieveAll(
            Require.beanPropertyEquals( BlobObservable.BLOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< SuspectBlobAzureTarget > getSuspectBlobAzureTargets()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( SuspectBlobAzureTarget.class ).retrieveAll(
            Require.beanPropertyEquals( BlobObservable.BLOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BlobS3TargetToVerify > getBlobS3TargetToVerifies()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BlobS3TargetToVerify.class ).retrieveAll(
            Require.beanPropertyEquals( BlobObservable.BLOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< ObsoleteBlobPool > getObsoleteBlobPools()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ObsoleteBlobPool.class ).retrieveAll(
            Require.beanPropertyEquals( BlobObservable.BLOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< SuspectBlobTape > getSuspectBlobTapes()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( SuspectBlobTape.class ).retrieveAll(
            Require.beanPropertyEquals( BlobObservable.BLOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BlobAzureTargetToVerify > getBlobAzureTargetToVerifies()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BlobAzureTargetToVerify.class ).retrieveAll(
            Require.beanPropertyEquals( BlobObservable.BLOB_ID, m_bean.getId() ) );
    }


    synchronized public long getByteOffset()
    {
        fetchBeanIfNull();
        return  m_bean.getByteOffset();
    }


    synchronized public String getChecksum()
    {
        fetchBeanIfNull();
        return  m_bean.getChecksum();
    }


    synchronized public ChecksumType getChecksumType()
    {
        fetchBeanIfNull();
        return  m_bean.getChecksumType();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public long getLength()
    {
        fetchBeanIfNull();
        return  m_bean.getLength();
    }


    synchronized public S3ObjectRM getObject()
    {
        if ( null != m_bean )
        {
            return new S3ObjectRM( m_bean.getObjectId(), m_serviceManager );
        }
        return new S3ObjectRM(
                Require.exists( Blob.class,
                        Blob.OBJECT_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( Blob.class ).attain( m_whereClause );
        }
    }


    synchronized public Blob unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private Blob m_bean;
}
