/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.shared.BlobObservable;
import com.spectralogic.s3.common.dao.domain.target.BlobAzureTarget;
import com.spectralogic.s3.common.dao.domain.target.BlobTarget;
import com.spectralogic.s3.common.dao.domain.target.SuspectBlobAzureTarget;
import com.spectralogic.s3.common.dao.domain.temp.BlobAzureTargetToVerify;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import java.util.UUID;


public class BlobAzureTargetRM
{
    public BlobAzureTargetRM( BlobAzureTarget bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public BlobAzureTargetRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    BlobAzureTargetRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public BlobRM getBlob()
    {
        if ( null != m_bean )
        {
            return new BlobRM( m_bean.getBlobId(), m_serviceManager );
        }
        return new BlobRM(
                Require.exists( BlobAzureTarget.class,
                        BlobObservable.BLOB_ID,
                        m_whereClause ),
                m_serviceManager );
    }


   synchronized public RetrieveBeansResult< SuspectBlobAzureTarget > getSuspectBlobAzureTargets()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( SuspectBlobAzureTarget.class ).retrieveAll(
            Require.beanPropertyEquals( Identifiable.ID, m_bean.getId() ) );
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


   synchronized public RetrieveBeansResult< BlobAzureTargetToVerify > getBlobAzureTargetToVerifies()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BlobAzureTargetToVerify.class ).retrieveAll(
            Require.beanPropertyEquals( Identifiable.ID, m_bean.getId() ) );
    }


    synchronized public AzureTargetRM getTarget()
    {
        if ( null != m_bean )
        {
            return new AzureTargetRM( m_bean.getTargetId(), m_serviceManager );
        }
        return new AzureTargetRM(
                Require.exists( BlobAzureTarget.class,
                        BlobTarget.TARGET_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( BlobAzureTarget.class ).attain( m_whereClause );
        }
    }


    synchronized public BlobAzureTarget unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private BlobAzureTarget m_bean;
}
