/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.BucketAcl;
import com.spectralogic.s3.common.dao.domain.ds3.BucketAclPermission;
import com.spectralogic.s3.common.dao.domain.ds3.UserIdObservable;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import java.util.UUID;


public class BucketAclRM
{
    public BucketAclRM( BucketAcl bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public BucketAclRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    BucketAclRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public BucketRM getBucket()
    {
        if ( null != m_bean )
        {
            return new BucketRM( m_bean.getBucketId(), m_serviceManager );
        }
        return new BucketRM(
                Require.exists( BucketAcl.class,
                        BucketAcl.BUCKET_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public GroupRM getGroup()
    {
        if ( null != m_bean )
        {
            return new GroupRM( m_bean.getGroupId(), m_serviceManager );
        }
        return new GroupRM(
                Require.exists( BucketAcl.class,
                        BucketAcl.GROUP_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public BucketAclPermission getPermission()
    {
        fetchBeanIfNull();
        return  m_bean.getPermission();
    }


    synchronized public UserRM getUser()
    {
        if ( null != m_bean )
        {
            return new UserRM( m_bean.getUserId(), m_serviceManager );
        }
        return new UserRM(
                Require.exists( BucketAcl.class,
                        UserIdObservable.USER_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( BucketAcl.class ).attain( m_whereClause );
        }
    }


    synchronized public BucketAcl unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private BucketAcl m_bean;
}
