/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.Bucket;
import com.spectralogic.s3.common.dao.domain.ds3.BucketAcl;
import com.spectralogic.s3.common.dao.domain.ds3.CanceledJob;
import com.spectralogic.s3.common.dao.domain.ds3.CompletedJob;
import com.spectralogic.s3.common.dao.domain.ds3.DegradedBlob;
import com.spectralogic.s3.common.dao.domain.ds3.DetailedLocalBlobDestination;
import com.spectralogic.s3.common.dao.domain.ds3.Job;
import com.spectralogic.s3.common.dao.domain.ds3.JobObservable;
import com.spectralogic.s3.common.dao.domain.ds3.LocalBlobDestination;
import com.spectralogic.s3.common.dao.domain.ds3.S3Object;
import com.spectralogic.s3.common.dao.domain.ds3.UserIdObservable;
import com.spectralogic.s3.common.dao.domain.notification.BucketChangesNotificationRegistration;
import com.spectralogic.s3.common.dao.domain.notification.BucketHistoryEvent;
import com.spectralogic.s3.common.dao.domain.notification.BucketNotificationRegistrationObservable;
import com.spectralogic.s3.common.dao.domain.pool.BlobPool;
import com.spectralogic.s3.common.dao.domain.pool.ObsoleteBlobPool;
import com.spectralogic.s3.common.dao.domain.pool.Pool;
import com.spectralogic.s3.common.dao.domain.pool.SuspectBlobPool;
import com.spectralogic.s3.common.dao.domain.shared.PersistenceTarget;
import com.spectralogic.s3.common.dao.domain.tape.RawImportTapeDirective;
import com.spectralogic.s3.common.dao.domain.tape.Tape;
import com.spectralogic.s3.common.dao.domain.target.AzureTargetBucketName;
import com.spectralogic.s3.common.dao.domain.target.AzureTargetReadPreference;
import com.spectralogic.s3.common.dao.domain.target.Ds3TargetReadPreference;
import com.spectralogic.s3.common.dao.domain.target.PublicCloudTargetBucketName;
import com.spectralogic.s3.common.dao.domain.target.S3TargetBucketName;
import com.spectralogic.s3.common.dao.domain.target.S3TargetReadPreference;
import com.spectralogic.s3.common.dao.domain.target.TargetReadPreference;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import java.util.Date;
import java.util.UUID;


public class BucketRM
{
    public BucketRM( Bucket bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public BucketRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    BucketRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


   synchronized public RetrieveBeansResult< RawImportTapeDirective > getRawImportTapeDirectives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( RawImportTapeDirective.class ).retrieveAll(
            Require.beanPropertyEquals( RawImportTapeDirective.BUCKET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BucketAcl > getBucketAcls()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BucketAcl.class ).retrieveAll(
            Require.beanPropertyEquals( BucketAcl.BUCKET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< Tape > getTapes()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( Tape.class ).retrieveAll(
            Require.beanPropertyEquals( PersistenceTarget.BUCKET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< AzureTargetReadPreference > getAzureTargetReadPreferences()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( AzureTargetReadPreference.class ).retrieveAll(
            Require.beanPropertyEquals( TargetReadPreference.BUCKET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BucketHistoryEvent > getBucketHistoryEvents()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BucketHistoryEvent.class ).retrieveAll(
            Require.beanPropertyEquals( BucketHistoryEvent.BUCKET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< DegradedBlob > getDegradedBlobs()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DegradedBlob.class ).retrieveAll(
            Require.beanPropertyEquals( DegradedBlob.BUCKET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< S3TargetBucketName > getS3TargetBucketNames()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( S3TargetBucketName.class ).retrieveAll(
            Require.beanPropertyEquals( PublicCloudTargetBucketName.BUCKET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< Job > getJobs()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( Job.class ).retrieveAll(
            Require.beanPropertyEquals( JobObservable.BUCKET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BlobPool > getBlobPools()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BlobPool.class ).retrieveAll(
            Require.beanPropertyEquals( BlobPool.BUCKET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< CanceledJob > getCanceledJobs()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( CanceledJob.class ).retrieveAll(
            Require.beanPropertyEquals( JobObservable.BUCKET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< S3Object > getS3Objects()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( S3Object.class ).retrieveAll(
            Require.beanPropertyEquals( S3Object.BUCKET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< SuspectBlobPool > getSuspectBlobPools()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( SuspectBlobPool.class ).retrieveAll(
            Require.beanPropertyEquals( BlobPool.BUCKET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< S3TargetReadPreference > getS3TargetReadPreferences()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( S3TargetReadPreference.class ).retrieveAll(
            Require.beanPropertyEquals( TargetReadPreference.BUCKET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< AzureTargetBucketName > getAzureTargetBucketNames()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( AzureTargetBucketName.class ).retrieveAll(
            Require.beanPropertyEquals( PublicCloudTargetBucketName.BUCKET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BucketChangesNotificationRegistration > getBucketChangesNotificationRegistrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BucketChangesNotificationRegistration.class ).retrieveAll(
            Require.beanPropertyEquals( BucketNotificationRegistrationObservable.BUCKET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< CompletedJob > getCompletedJobs()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( CompletedJob.class ).retrieveAll(
            Require.beanPropertyEquals( JobObservable.BUCKET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< ObsoleteBlobPool > getObsoleteBlobPools()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ObsoleteBlobPool.class ).retrieveAll(
            Require.beanPropertyEquals( BlobPool.BUCKET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< Pool > getPools()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( Pool.class ).retrieveAll(
            Require.beanPropertyEquals( PersistenceTarget.BUCKET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< Ds3TargetReadPreference > getDs3TargetReadPreferences()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( Ds3TargetReadPreference.class ).retrieveAll(
            Require.beanPropertyEquals( TargetReadPreference.BUCKET_ID, m_bean.getId() ) );
    }


    synchronized public Date getCreationDate()
    {
        fetchBeanIfNull();
        return  m_bean.getCreationDate();
    }


    synchronized public DataPolicyRM getDataPolicy()
    {
        if ( null != m_bean )
        {
            return new DataPolicyRM( m_bean.getDataPolicyId(), m_serviceManager );
        }
        return new DataPolicyRM(
                Require.exists( Bucket.class,
                        Bucket.DATA_POLICY_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public Boolean getEmpty()
    {
        fetchBeanIfNull();
        return  m_bean.getEmpty();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


   synchronized public RetrieveBeansResult< LocalBlobDestination > getLocalBlobDestinations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( LocalBlobDestination.class ).retrieveAll(
            Require.beanPropertyEquals( LocalBlobDestination.ISOLATED_BUCKET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< DetailedLocalBlobDestination > getDetailedLocalBlobDestinations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DetailedLocalBlobDestination.class ).retrieveAll(
            Require.beanPropertyEquals( LocalBlobDestination.ISOLATED_BUCKET_ID, m_bean.getId() ) );
    }


    synchronized public Long getLastPreferredChunkSizeInBytes()
    {
        fetchBeanIfNull();
        return  m_bean.getLastPreferredChunkSizeInBytes();
    }


    synchronized public Long getLogicalUsedCapacity()
    {
        fetchBeanIfNull();
        return  m_bean.getLogicalUsedCapacity();
    }


    synchronized public String getName()
    {
        fetchBeanIfNull();
        return  m_bean.getName();
    }


    synchronized public boolean isProtected()
    {
        fetchBeanIfNull();
        return  m_bean.isProtected();
    }


    synchronized public UserRM getUser()
    {
        if ( null != m_bean )
        {
            return new UserRM( m_bean.getUserId(), m_serviceManager );
        }
        return new UserRM(
                Require.exists( Bucket.class,
                        UserIdObservable.USER_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( Bucket.class ).attain( m_whereClause );
        }
    }


    synchronized public Bucket unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private Bucket m_bean;
}
