/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.planner.CacheFilesystem;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import java.util.UUID;


public class CacheFilesystemRM
{
    public CacheFilesystemRM( CacheFilesystem bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public CacheFilesystemRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    CacheFilesystemRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public double getAutoReclaimInitiateThreshold()
    {
        fetchBeanIfNull();
        return  m_bean.getAutoReclaimInitiateThreshold();
    }


    synchronized public double getAutoReclaimTerminateThreshold()
    {
        fetchBeanIfNull();
        return  m_bean.getAutoReclaimTerminateThreshold();
    }


    synchronized public boolean getCacheSafetyEnabled()
    {
        fetchBeanIfNull();
        return  m_bean.getCacheSafetyEnabled();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public Long getMaxCapacityInBytes()
    {
        fetchBeanIfNull();
        return  m_bean.getMaxCapacityInBytes();
    }


    synchronized public Double getMaxPercentUtilizationOfFilesystem()
    {
        fetchBeanIfNull();
        return  m_bean.getMaxPercentUtilizationOfFilesystem();
    }


    synchronized public boolean getNeedsReconcile()
    {
        fetchBeanIfNull();
        return  m_bean.getNeedsReconcile();
    }


    synchronized public NodeRM getNode()
    {
        if ( null != m_bean )
        {
            return new NodeRM( m_bean.getNodeId(), m_serviceManager );
        }
        return new NodeRM(
                Require.exists( CacheFilesystem.class,
                        CacheFilesystem.NODE_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public String getPath()
    {
        fetchBeanIfNull();
        return  m_bean.getPath();
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( CacheFilesystem.class ).attain( m_whereClause );
        }
    }


    synchronized public CacheFilesystem unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private CacheFilesystem m_bean;
}
