/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.AzureDataReplicationRule;
import com.spectralogic.s3.common.dao.domain.ds3.BlobStoreTaskPriority;
import com.spectralogic.s3.common.dao.domain.ds3.Bucket;
import com.spectralogic.s3.common.dao.domain.ds3.DataPersistenceRule;
import com.spectralogic.s3.common.dao.domain.ds3.DataPlacement;
import com.spectralogic.s3.common.dao.domain.ds3.DataPolicy;
import com.spectralogic.s3.common.dao.domain.ds3.DataPolicyAcl;
import com.spectralogic.s3.common.dao.domain.ds3.Ds3DataReplicationRule;
import com.spectralogic.s3.common.dao.domain.ds3.S3DataReplicationRule;
import com.spectralogic.s3.common.dao.domain.ds3.User;
import com.spectralogic.s3.common.dao.domain.ds3.VersioningLevel;
import com.spectralogic.s3.common.dao.domain.pool.ImportPoolDirective;
import com.spectralogic.s3.common.dao.domain.shared.ImportDirective;
import com.spectralogic.s3.common.dao.domain.tape.ImportTapeDirective;
import com.spectralogic.s3.common.dao.domain.tape.RawImportTapeDirective;
import com.spectralogic.s3.common.dao.domain.target.ImportAzureTargetDirective;
import com.spectralogic.s3.common.dao.domain.target.ImportS3TargetDirective;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import com.spectralogic.util.security.ChecksumType;
import java.util.Date;
import java.util.UUID;


public class DataPolicyRM
{
    public DataPolicyRM( DataPolicy bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public DataPolicyRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    DataPolicyRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public boolean isAlwaysForcePutJobCreation()
    {
        fetchBeanIfNull();
        return  m_bean.isAlwaysForcePutJobCreation();
    }


    synchronized public boolean isAlwaysMinimizeSpanningAcrossMedia()
    {
        fetchBeanIfNull();
        return  m_bean.isAlwaysMinimizeSpanningAcrossMedia();
    }


    synchronized public boolean isBlobbingEnabled()
    {
        fetchBeanIfNull();
        return  m_bean.isBlobbingEnabled();
    }


    synchronized public ChecksumType getChecksumType()
    {
        fetchBeanIfNull();
        return  m_bean.getChecksumType();
    }


    synchronized public Date getCreationDate()
    {
        fetchBeanIfNull();
        return  m_bean.getCreationDate();
    }


   synchronized public RetrieveBeansResult< ImportTapeDirective > getImportTapeDirectives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ImportTapeDirective.class ).retrieveAll(
            Require.beanPropertyEquals( ImportDirective.DATA_POLICY_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< RawImportTapeDirective > getRawImportTapeDirectives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( RawImportTapeDirective.class ).retrieveAll(
            Require.beanPropertyEquals( ImportDirective.DATA_POLICY_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< Bucket > getBuckets()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( Bucket.class ).retrieveAll(
            Require.beanPropertyEquals( Bucket.DATA_POLICY_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< DataPolicyAcl > getDataPolicyAcls()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DataPolicyAcl.class ).retrieveAll(
            Require.beanPropertyEquals( DataPolicyAcl.DATA_POLICY_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< S3DataReplicationRule > getS3DataReplicationRules()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( S3DataReplicationRule.class ).retrieveAll(
            Require.beanPropertyEquals( DataPlacement.DATA_POLICY_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< ImportAzureTargetDirective > getImportAzureTargetDirectives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ImportAzureTargetDirective.class ).retrieveAll(
            Require.beanPropertyEquals( ImportDirective.DATA_POLICY_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< Ds3DataReplicationRule > getDs3DataReplicationRules()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( Ds3DataReplicationRule.class ).retrieveAll(
            Require.beanPropertyEquals( DataPlacement.DATA_POLICY_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< AzureDataReplicationRule > getAzureDataReplicationRules()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( AzureDataReplicationRule.class ).retrieveAll(
            Require.beanPropertyEquals( DataPlacement.DATA_POLICY_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< DataPersistenceRule > getDataPersistenceRules()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DataPersistenceRule.class ).retrieveAll(
            Require.beanPropertyEquals( DataPlacement.DATA_POLICY_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< ImportPoolDirective > getImportPoolDirectives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ImportPoolDirective.class ).retrieveAll(
            Require.beanPropertyEquals( ImportDirective.DATA_POLICY_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< ImportS3TargetDirective > getImportS3TargetDirectives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ImportS3TargetDirective.class ).retrieveAll(
            Require.beanPropertyEquals( ImportDirective.DATA_POLICY_ID, m_bean.getId() ) );
    }


    synchronized public Long getDefaultBlobSize()
    {
        fetchBeanIfNull();
        return  m_bean.getDefaultBlobSize();
    }


   synchronized public RetrieveBeansResult< User > getUsers()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( User.class ).retrieveAll(
            Require.beanPropertyEquals( User.DEFAULT_DATA_POLICY_ID, m_bean.getId() ) );
    }


    synchronized public BlobStoreTaskPriority getDefaultGetJobPriority()
    {
        fetchBeanIfNull();
        return  m_bean.getDefaultGetJobPriority();
    }


    synchronized public BlobStoreTaskPriority getDefaultPutJobPriority()
    {
        fetchBeanIfNull();
        return  m_bean.getDefaultPutJobPriority();
    }


    synchronized public boolean isDefaultVerifyAfterWrite()
    {
        fetchBeanIfNull();
        return  m_bean.isDefaultVerifyAfterWrite();
    }


    synchronized public BlobStoreTaskPriority getDefaultVerifyJobPriority()
    {
        fetchBeanIfNull();
        return  m_bean.getDefaultVerifyJobPriority();
    }


    synchronized public boolean isEndToEndCrcRequired()
    {
        fetchBeanIfNull();
        return  m_bean.isEndToEndCrcRequired();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public int getMaxVersionsToKeep()
    {
        fetchBeanIfNull();
        return  m_bean.getMaxVersionsToKeep();
    }


    synchronized public String getName()
    {
        fetchBeanIfNull();
        return  m_bean.getName();
    }


    synchronized public BlobStoreTaskPriority getRebuildPriority()
    {
        fetchBeanIfNull();
        return  m_bean.getRebuildPriority();
    }


    synchronized public VersioningLevel getVersioning()
    {
        fetchBeanIfNull();
        return  m_bean.getVersioning();
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( DataPolicy.class ).attain( m_whereClause );
        }
    }


    synchronized public DataPolicy unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private DataPolicy m_bean;
}
