/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.AutoInspectMode;
import com.spectralogic.s3.common.dao.domain.ds3.BlobStoreTaskPriority;
import com.spectralogic.s3.common.dao.domain.ds3.DataPathBackend;
import com.spectralogic.s3.common.dao.domain.ds3.UnavailableMediaUsagePolicy;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import java.util.Date;
import java.util.UUID;


public class DataPathBackendRM
{
    public DataPathBackendRM( DataPathBackend bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public DataPathBackendRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    DataPathBackendRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public boolean isActivated()
    {
        fetchBeanIfNull();
        return  m_bean.isActivated();
    }


    synchronized public boolean isAllowNewJobRequests()
    {
        fetchBeanIfNull();
        return  m_bean.isAllowNewJobRequests();
    }


    synchronized public Integer getAutoActivateTimeoutInMins()
    {
        fetchBeanIfNull();
        return  m_bean.getAutoActivateTimeoutInMins();
    }


    synchronized public AutoInspectMode getAutoInspect()
    {
        fetchBeanIfNull();
        return  m_bean.getAutoInspect();
    }


    synchronized public int getCacheAvailableRetryAfterInSeconds()
    {
        fetchBeanIfNull();
        return  m_bean.getCacheAvailableRetryAfterInSeconds();
    }


    synchronized public BlobStoreTaskPriority getDefaultVerifyDataAfterImport()
    {
        fetchBeanIfNull();
        return  m_bean.getDefaultVerifyDataAfterImport();
    }


    synchronized public boolean isDefaultVerifyDataPriorToImport()
    {
        fetchBeanIfNull();
        return  m_bean.isDefaultVerifyDataPriorToImport();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public UUID getInstanceId()
    {
        fetchBeanIfNull();
        return  m_bean.getInstanceId();
    }


    synchronized public double getIomCacheLimitationPercent()
    {
        fetchBeanIfNull();
        return  m_bean.getIomCacheLimitationPercent();
    }


    synchronized public boolean isIomEnabled()
    {
        fetchBeanIfNull();
        return  m_bean.isIomEnabled();
    }


    synchronized public Date getLastHeartbeat()
    {
        fetchBeanIfNull();
        return  m_bean.getLastHeartbeat();
    }


    synchronized public int getMaxAggregatedBlobsPerChunk()
    {
        fetchBeanIfNull();
        return  m_bean.getMaxAggregatedBlobsPerChunk();
    }


    synchronized public int getMaxNumberOfConcurrentJobs()
    {
        fetchBeanIfNull();
        return  m_bean.getMaxNumberOfConcurrentJobs();
    }


    synchronized public Integer getPartiallyVerifyLastPercentOfTapes()
    {
        fetchBeanIfNull();
        return  m_bean.getPartiallyVerifyLastPercentOfTapes();
    }


    synchronized public boolean getPoolSafetyEnabled()
    {
        fetchBeanIfNull();
        return  m_bean.getPoolSafetyEnabled();
    }


    synchronized public UnavailableMediaUsagePolicy getUnavailableMediaPolicy()
    {
        fetchBeanIfNull();
        return  m_bean.getUnavailableMediaPolicy();
    }


    synchronized public int getUnavailablePoolMaxJobRetryInMins()
    {
        fetchBeanIfNull();
        return  m_bean.getUnavailablePoolMaxJobRetryInMins();
    }


    synchronized public int getUnavailableTapePartitionMaxJobRetryInMins()
    {
        fetchBeanIfNull();
        return  m_bean.getUnavailableTapePartitionMaxJobRetryInMins();
    }


    synchronized public boolean isVerifyCheckpointBeforeRead()
    {
        fetchBeanIfNull();
        return  m_bean.isVerifyCheckpointBeforeRead();
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( DataPathBackend.class ).attain( m_whereClause );
        }
    }


    synchronized public DataPathBackend unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private DataPathBackend m_bean;
}
