/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.DegradedBlob;
import com.spectralogic.s3.common.dao.domain.shared.BlobObservable;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import java.util.UUID;


public class DegradedBlobRM
{
    public DegradedBlobRM( DegradedBlob bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public DegradedBlobRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    DegradedBlobRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public AzureDataReplicationRuleRM getAzureReplicationRule()
    {
        if ( null != m_bean )
        {
            return new AzureDataReplicationRuleRM( m_bean.getAzureReplicationRuleId(), m_serviceManager );
        }
        return new AzureDataReplicationRuleRM(
                Require.exists( DegradedBlob.class,
                        DegradedBlob.AZURE_REPLICATION_RULE_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public BlobRM getBlob()
    {
        if ( null != m_bean )
        {
            return new BlobRM( m_bean.getBlobId(), m_serviceManager );
        }
        return new BlobRM(
                Require.exists( DegradedBlob.class,
                        BlobObservable.BLOB_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public BucketRM getBucket()
    {
        if ( null != m_bean )
        {
            return new BucketRM( m_bean.getBucketId(), m_serviceManager );
        }
        return new BucketRM(
                Require.exists( DegradedBlob.class,
                        DegradedBlob.BUCKET_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public Ds3DataReplicationRuleRM getDs3ReplicationRule()
    {
        if ( null != m_bean )
        {
            return new Ds3DataReplicationRuleRM( m_bean.getDs3ReplicationRuleId(), m_serviceManager );
        }
        return new Ds3DataReplicationRuleRM(
                Require.exists( DegradedBlob.class,
                        DegradedBlob.DS3_REPLICATION_RULE_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public DataPersistenceRuleRM getPersistenceRule()
    {
        if ( null != m_bean )
        {
            return new DataPersistenceRuleRM( m_bean.getPersistenceRuleId(), m_serviceManager );
        }
        return new DataPersistenceRuleRM(
                Require.exists( DegradedBlob.class,
                        DegradedBlob.PERSISTENCE_RULE_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public S3DataReplicationRuleRM getS3ReplicationRule()
    {
        if ( null != m_bean )
        {
            return new S3DataReplicationRuleRM( m_bean.getS3ReplicationRuleId(), m_serviceManager );
        }
        return new S3DataReplicationRuleRM(
                Require.exists( DegradedBlob.class,
                        DegradedBlob.S3_REPLICATION_RULE_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( DegradedBlob.class ).attain( m_whereClause );
        }
    }


    synchronized public DegradedBlob unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private DegradedBlob m_bean;
}
