/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.BlobStoreTaskPriority;
import com.spectralogic.s3.common.dao.domain.ds3.DetailedJobEntry;
import com.spectralogic.s3.common.dao.domain.ds3.JobChunkBlobStoreState;
import com.spectralogic.s3.common.dao.domain.ds3.JobEntry;
import com.spectralogic.s3.common.dao.domain.ds3.JobRequestType;
import com.spectralogic.s3.common.dao.domain.planner.CacheEntryState;
import com.spectralogic.s3.common.dao.domain.shared.BlobObservable;
import com.spectralogic.s3.common.dao.domain.shared.ReadFromObservable;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import java.util.Date;
import java.util.UUID;


public class DetailedJobEntryRM
{
    public DetailedJobEntryRM( DetailedJobEntry bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public DetailedJobEntryRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    DetailedJobEntryRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public BlobRM getBlob()
    {
        if ( null != m_bean )
        {
            return new BlobRM( m_bean.getBlobId(), m_serviceManager );
        }
        return new BlobRM(
                Require.exists( DetailedJobEntry.class,
                        BlobObservable.BLOB_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public JobChunkBlobStoreState getBlobStoreState()
    {
        fetchBeanIfNull();
        return  m_bean.getBlobStoreState();
    }


    synchronized public CacheEntryState getCacheState()
    {
        fetchBeanIfNull();
        return  m_bean.getCacheState();
    }


    synchronized public int getChunkNumber()
    {
        fetchBeanIfNull();
        return  m_bean.getChunkNumber();
    }


    synchronized public Date getCreatedAt()
    {
        fetchBeanIfNull();
        return  m_bean.getCreatedAt();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public JobRM getJob()
    {
        if ( null != m_bean )
        {
            return new JobRM( m_bean.getJobId(), m_serviceManager );
        }
        return new JobRM(
                Require.exists( DetailedJobEntry.class,
                        JobEntry.JOB_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public long getLength()
    {
        fetchBeanIfNull();
        return  m_bean.getLength();
    }


    synchronized public NodeRM getNode()
    {
        if ( null != m_bean )
        {
            return new NodeRM( m_bean.getNodeId(), m_serviceManager );
        }
        return new NodeRM(
                Require.exists( DetailedJobEntry.class,
                        JobEntry.NODE_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public S3ObjectRM getObject()
    {
        if ( null != m_bean )
        {
            return new S3ObjectRM( m_bean.getObjectId(), m_serviceManager );
        }
        return new S3ObjectRM(
                Require.exists( DetailedJobEntry.class,
                        DetailedJobEntry.OBJECT_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public boolean isPendingTargetCommit()
    {
        fetchBeanIfNull();
        return  m_bean.isPendingTargetCommit();
    }


    synchronized public BlobStoreTaskPriority getPriority()
    {
        fetchBeanIfNull();
        return  m_bean.getPriority();
    }


    synchronized public AzureTargetRM getReadFromAzureTarget()
    {
        if ( null != m_bean )
        {
            return new AzureTargetRM( m_bean.getReadFromAzureTargetId(), m_serviceManager );
        }
        return new AzureTargetRM(
                Require.exists( DetailedJobEntry.class,
                        ReadFromObservable.READ_FROM_AZURE_TARGET_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public Ds3TargetRM getReadFromDs3Target()
    {
        if ( null != m_bean )
        {
            return new Ds3TargetRM( m_bean.getReadFromDs3TargetId(), m_serviceManager );
        }
        return new Ds3TargetRM(
                Require.exists( DetailedJobEntry.class,
                        ReadFromObservable.READ_FROM_DS3_TARGET_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public PoolRM getReadFromPool()
    {
        if ( null != m_bean )
        {
            return new PoolRM( m_bean.getReadFromPoolId(), m_serviceManager );
        }
        return new PoolRM(
                Require.exists( DetailedJobEntry.class,
                        ReadFromObservable.READ_FROM_POOL_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public S3TargetRM getReadFromS3Target()
    {
        if ( null != m_bean )
        {
            return new S3TargetRM( m_bean.getReadFromS3TargetId(), m_serviceManager );
        }
        return new S3TargetRM(
                Require.exists( DetailedJobEntry.class,
                        ReadFromObservable.READ_FROM_S3_TARGET_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public TapeRM getReadFromTape()
    {
        if ( null != m_bean )
        {
            return new TapeRM( m_bean.getReadFromTapeId(), m_serviceManager );
        }
        return new TapeRM(
                Require.exists( DetailedJobEntry.class,
                        ReadFromObservable.READ_FROM_TAPE_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public JobRequestType getRequestType()
    {
        fetchBeanIfNull();
        return  m_bean.getRequestType();
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( DetailedJobEntry.class ).attain( m_whereClause );
        }
    }


    synchronized public DetailedJobEntry unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private DetailedJobEntry m_bean;
}
