/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.BlobStoreTaskPriority;
import com.spectralogic.s3.common.dao.domain.ds3.DetailedAzureBlobDestination;
import com.spectralogic.s3.common.dao.domain.ds3.JobChunkBlobStoreState;
import com.spectralogic.s3.common.dao.domain.ds3.RemoteBlobDestination;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import java.util.Date;
import java.util.UUID;


public class DetailedAzureBlobDestinationRM
{
    public DetailedAzureBlobDestinationRM( DetailedAzureBlobDestination bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public DetailedAzureBlobDestinationRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    DetailedAzureBlobDestinationRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public JobChunkBlobStoreState getBlobStoreState()
    {
        fetchBeanIfNull();
        return  m_bean.getBlobStoreState();
    }


    synchronized public Date getCreatedAt()
    {
        fetchBeanIfNull();
        return  m_bean.getCreatedAt();
    }


    synchronized public JobEntryRM getEntry()
    {
        if ( null != m_bean )
        {
            return new JobEntryRM( m_bean.getEntryId(), m_serviceManager );
        }
        return new JobEntryRM(
                Require.exists( DetailedAzureBlobDestination.class,
                        RemoteBlobDestination.ENTRY_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public JobRM getJob()
    {
        if ( null != m_bean )
        {
            return new JobRM( m_bean.getJobId(), m_serviceManager );
        }
        return new JobRM(
                Require.exists( DetailedAzureBlobDestination.class,
                        DetailedAzureBlobDestination.JOB_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public BlobStoreTaskPriority getPriority()
    {
        fetchBeanIfNull();
        return  m_bean.getPriority();
    }


    synchronized public UUID getRuleId()
    {
        fetchBeanIfNull();
        return  m_bean.getRuleId();
    }


    synchronized public AzureTargetRM getTarget()
    {
        if ( null != m_bean )
        {
            return new AzureTargetRM( m_bean.getTargetId(), m_serviceManager );
        }
        return new AzureTargetRM(
                Require.exists( DetailedAzureBlobDestination.class,
                        RemoteBlobDestination.TARGET_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( DetailedAzureBlobDestination.class ).attain( m_whereClause );
        }
    }


    synchronized public DetailedAzureBlobDestination unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private DetailedAzureBlobDestination m_bean;
}
