/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.DataPlacement;
import com.spectralogic.s3.common.dao.domain.ds3.DataPlacementRuleState;
import com.spectralogic.s3.common.dao.domain.ds3.DataReplicationRule;
import com.spectralogic.s3.common.dao.domain.ds3.DataReplicationRuleType;
import com.spectralogic.s3.common.dao.domain.ds3.DegradedBlob;
import com.spectralogic.s3.common.dao.domain.ds3.Ds3DataReplicationRule;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import java.util.UUID;


public class Ds3DataReplicationRuleRM
{
    public Ds3DataReplicationRuleRM( Ds3DataReplicationRule bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public Ds3DataReplicationRuleRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    Ds3DataReplicationRuleRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public DataPolicyRM getDataPolicy()
    {
        if ( null != m_bean )
        {
            return new DataPolicyRM( m_bean.getDataPolicyId(), m_serviceManager );
        }
        return new DataPolicyRM(
                Require.exists( Ds3DataReplicationRule.class,
                        DataPlacement.DATA_POLICY_ID,
                        m_whereClause ),
                m_serviceManager );
    }


   synchronized public RetrieveBeansResult< DegradedBlob > getDegradedBlobs()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DegradedBlob.class ).retrieveAll(
            Require.beanPropertyEquals( DegradedBlob.DS3_REPLICATION_RULE_ID, m_bean.getId() ) );
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public boolean isReplicateDeletes()
    {
        fetchBeanIfNull();
        return  m_bean.isReplicateDeletes();
    }


    synchronized public DataPlacementRuleState getState()
    {
        fetchBeanIfNull();
        return  m_bean.getState();
    }


    synchronized public String getTargetDataPolicy()
    {
        fetchBeanIfNull();
        return  m_bean.getTargetDataPolicy();
    }


    synchronized public Ds3TargetRM getTarget()
    {
        if ( null != m_bean )
        {
            return new Ds3TargetRM( m_bean.getTargetId(), m_serviceManager );
        }
        return new Ds3TargetRM(
                Require.exists( Ds3DataReplicationRule.class,
                        DataReplicationRule.TARGET_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public DataReplicationRuleType getType()
    {
        fetchBeanIfNull();
        return  m_bean.getType();
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( Ds3DataReplicationRule.class ).attain( m_whereClause );
        }
    }


    synchronized public Ds3DataReplicationRule unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private Ds3DataReplicationRule m_bean;
}
