/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.UserIdObservable;
import com.spectralogic.s3.common.dao.domain.notification.Ds3TargetFailureNotificationRegistration;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.http.HttpResponseFormatType;
import com.spectralogic.util.http.RequestType;
import com.spectralogic.util.lang.NamingConventionType;
import java.util.Date;
import java.util.UUID;


public class Ds3TargetFailureNotificationRegistrationRM
{
    public Ds3TargetFailureNotificationRegistrationRM( Ds3TargetFailureNotificationRegistration bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public Ds3TargetFailureNotificationRegistrationRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    Ds3TargetFailureNotificationRegistrationRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public Date getCreationDate()
    {
        fetchBeanIfNull();
        return  m_bean.getCreationDate();
    }


    synchronized public HttpResponseFormatType getFormat()
    {
        fetchBeanIfNull();
        return  m_bean.getFormat();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public String getLastFailure()
    {
        fetchBeanIfNull();
        return  m_bean.getLastFailure();
    }


    synchronized public Integer getLastHttpResponseCode()
    {
        fetchBeanIfNull();
        return  m_bean.getLastHttpResponseCode();
    }


    synchronized public Date getLastNotification()
    {
        fetchBeanIfNull();
        return  m_bean.getLastNotification();
    }


    synchronized public NamingConventionType getNamingConvention()
    {
        fetchBeanIfNull();
        return  m_bean.getNamingConvention();
    }


    synchronized public String getNotificationEndPoint()
    {
        fetchBeanIfNull();
        return  m_bean.getNotificationEndPoint();
    }


    synchronized public RequestType getNotificationHttpMethod()
    {
        fetchBeanIfNull();
        return  m_bean.getNotificationHttpMethod();
    }


    synchronized public int getNumberOfFailuresSinceLastSuccess()
    {
        fetchBeanIfNull();
        return  m_bean.getNumberOfFailuresSinceLastSuccess();
    }


    synchronized public UserRM getUser()
    {
        if ( null != m_bean )
        {
            return new UserRM( m_bean.getUserId(), m_serviceManager );
        }
        return new UserRM(
                Require.exists( Ds3TargetFailureNotificationRegistration.class,
                        UserIdObservable.USER_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( Ds3TargetFailureNotificationRegistration.class ).attain( m_whereClause );
        }
    }


    synchronized public Ds3TargetFailureNotificationRegistration unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private Ds3TargetFailureNotificationRegistration m_bean;
}
