/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.DataReplicationRule;
import com.spectralogic.s3.common.dao.domain.ds3.DetailedDs3BlobDestination;
import com.spectralogic.s3.common.dao.domain.ds3.DetailedJobEntry;
import com.spectralogic.s3.common.dao.domain.ds3.Ds3BlobDestination;
import com.spectralogic.s3.common.dao.domain.ds3.Ds3DataReplicationRule;
import com.spectralogic.s3.common.dao.domain.ds3.JobEntry;
import com.spectralogic.s3.common.dao.domain.ds3.RemoteBlobDestination;
import com.spectralogic.s3.common.dao.domain.shared.Quiesced;
import com.spectralogic.s3.common.dao.domain.shared.ReadFromObservable;
import com.spectralogic.s3.common.dao.domain.target.BlobDs3Target;
import com.spectralogic.s3.common.dao.domain.target.BlobTarget;
import com.spectralogic.s3.common.dao.domain.target.Ds3Target;
import com.spectralogic.s3.common.dao.domain.target.Ds3TargetAccessControlReplication;
import com.spectralogic.s3.common.dao.domain.target.Ds3TargetFailure;
import com.spectralogic.s3.common.dao.domain.target.Ds3TargetReadPreference;
import com.spectralogic.s3.common.dao.domain.target.SuspectBlobDs3Target;
import com.spectralogic.s3.common.dao.domain.target.TargetFailure;
import com.spectralogic.s3.common.dao.domain.target.TargetReadPreference;
import com.spectralogic.s3.common.dao.domain.target.TargetReadPreferenceType;
import com.spectralogic.s3.common.dao.domain.target.TargetState;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import java.util.UUID;


public class Ds3TargetRM
{
    public Ds3TargetRM( Ds3Target bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public Ds3TargetRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    Ds3TargetRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public Ds3TargetAccessControlReplication getAccessControlReplication()
    {
        fetchBeanIfNull();
        return  m_bean.getAccessControlReplication();
    }


    synchronized public String getAdminAuthId()
    {
        fetchBeanIfNull();
        return  m_bean.getAdminAuthId();
    }


    synchronized public String getAdminSecretKey()
    {
        fetchBeanIfNull();
        return  m_bean.getAdminSecretKey();
    }


    synchronized public String getDataPathEndPoint()
    {
        fetchBeanIfNull();
        return  m_bean.getDataPathEndPoint();
    }


    synchronized public boolean isDataPathHttps()
    {
        fetchBeanIfNull();
        return  m_bean.isDataPathHttps();
    }


    synchronized public Integer getDataPathPort()
    {
        fetchBeanIfNull();
        return  m_bean.getDataPathPort();
    }


    synchronized public String getDataPathProxy()
    {
        fetchBeanIfNull();
        return  m_bean.getDataPathProxy();
    }


    synchronized public boolean isDataPathVerifyCertificate()
    {
        fetchBeanIfNull();
        return  m_bean.isDataPathVerifyCertificate();
    }


    synchronized public TargetReadPreferenceType getDefaultReadPreference()
    {
        fetchBeanIfNull();
        return  m_bean.getDefaultReadPreference();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public String getName()
    {
        fetchBeanIfNull();
        return  m_bean.getName();
    }


    synchronized public boolean isPermitGoingOutOfSync()
    {
        fetchBeanIfNull();
        return  m_bean.isPermitGoingOutOfSync();
    }


    synchronized public Quiesced getQuiesced()
    {
        fetchBeanIfNull();
        return  m_bean.getQuiesced();
    }


   synchronized public RetrieveBeansResult< DetailedJobEntry > getDetailedJobEntries()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DetailedJobEntry.class ).retrieveAll(
            Require.beanPropertyEquals( ReadFromObservable.READ_FROM_DS3_TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< JobEntry > getJobEntries()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( JobEntry.class ).retrieveAll(
            Require.beanPropertyEquals( ReadFromObservable.READ_FROM_DS3_TARGET_ID, m_bean.getId() ) );
    }


    synchronized public String getReplicatedUserDefaultDataPolicy()
    {
        fetchBeanIfNull();
        return  m_bean.getReplicatedUserDefaultDataPolicy();
    }


    synchronized public TargetState getState()
    {
        fetchBeanIfNull();
        return  m_bean.getState();
    }


   synchronized public RetrieveBeansResult< SuspectBlobDs3Target > getSuspectBlobDs3Targets()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( SuspectBlobDs3Target.class ).retrieveAll(
            Require.beanPropertyEquals( BlobTarget.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< Ds3BlobDestination > getDs3BlobDestinations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( Ds3BlobDestination.class ).retrieveAll(
            Require.beanPropertyEquals( RemoteBlobDestination.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< DetailedDs3BlobDestination > getDetailedDs3BlobDestinations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DetailedDs3BlobDestination.class ).retrieveAll(
            Require.beanPropertyEquals( RemoteBlobDestination.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< Ds3DataReplicationRule > getDs3DataReplicationRules()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( Ds3DataReplicationRule.class ).retrieveAll(
            Require.beanPropertyEquals( DataReplicationRule.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BlobDs3Target > getBlobDs3Targets()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BlobDs3Target.class ).retrieveAll(
            Require.beanPropertyEquals( BlobTarget.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< Ds3TargetFailure > getDs3TargetFailures()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( Ds3TargetFailure.class ).retrieveAll(
            Require.beanPropertyEquals( TargetFailure.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< Ds3TargetReadPreference > getDs3TargetReadPreferences()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( Ds3TargetReadPreference.class ).retrieveAll(
            Require.beanPropertyEquals( TargetReadPreference.TARGET_ID, m_bean.getId() ) );
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( Ds3Target.class ).attain( m_whereClause );
        }
    }


    synchronized public Ds3Target unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private Ds3Target m_bean;
}
