/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.GroupMember;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import java.util.UUID;


public class GroupMemberRM
{
    public GroupMemberRM( GroupMember bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public GroupMemberRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    GroupMemberRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public GroupRM getGroup()
    {
        if ( null != m_bean )
        {
            return new GroupRM( m_bean.getGroupId(), m_serviceManager );
        }
        return new GroupRM(
                Require.exists( GroupMember.class,
                        GroupMember.GROUP_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public GroupRM getMemberGroup()
    {
        if ( null != m_bean )
        {
            return new GroupRM( m_bean.getMemberGroupId(), m_serviceManager );
        }
        return new GroupRM(
                Require.exists( GroupMember.class,
                        GroupMember.MEMBER_GROUP_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public UserRM getMemberUser()
    {
        if ( null != m_bean )
        {
            return new UserRM( m_bean.getMemberUserId(), m_serviceManager );
        }
        return new UserRM(
                Require.exists( GroupMember.class,
                        GroupMember.MEMBER_USER_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( GroupMember.class ).attain( m_whereClause );
        }
    }


    synchronized public GroupMember unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private GroupMember m_bean;
}
