/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.BucketAcl;
import com.spectralogic.s3.common.dao.domain.ds3.DataPolicyAcl;
import com.spectralogic.s3.common.dao.domain.ds3.Group;
import com.spectralogic.s3.common.dao.domain.ds3.GroupMember;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import java.util.UUID;


public class GroupRM
{
    public GroupRM( Group bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public GroupRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    GroupRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public boolean isBuiltIn()
    {
        fetchBeanIfNull();
        return  m_bean.isBuiltIn();
    }


   synchronized public RetrieveBeansResult< DataPolicyAcl > getDataPolicyAcls()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DataPolicyAcl.class ).retrieveAll(
            Require.beanPropertyEquals( DataPolicyAcl.GROUP_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< GroupMember > getGroupMembers()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( GroupMember.class ).retrieveAll(
            Require.beanPropertyEquals( GroupMember.GROUP_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BucketAcl > getBucketAcls()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BucketAcl.class ).retrieveAll(
            Require.beanPropertyEquals( BucketAcl.GROUP_ID, m_bean.getId() ) );
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public String getName()
    {
        fetchBeanIfNull();
        return  m_bean.getName();
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( Group.class ).attain( m_whereClause );
        }
    }


    synchronized public Group unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private Group m_bean;
}
