/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.BlobStoreTaskPriority;
import com.spectralogic.s3.common.dao.domain.shared.ImportDirective;
import com.spectralogic.s3.common.dao.domain.shared.ImportPublicCloudTargetDirective;
import com.spectralogic.s3.common.dao.domain.target.ImportS3TargetDirective;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import java.util.UUID;


public class ImportS3TargetDirectiveRM
{
    public ImportS3TargetDirectiveRM( ImportS3TargetDirective bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public ImportS3TargetDirectiveRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    ImportS3TargetDirectiveRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public String getCloudBucketName()
    {
        fetchBeanIfNull();
        return  m_bean.getCloudBucketName();
    }


    synchronized public DataPolicyRM getDataPolicy()
    {
        if ( null != m_bean )
        {
            return new DataPolicyRM( m_bean.getDataPolicyId(), m_serviceManager );
        }
        return new DataPolicyRM(
                Require.exists( ImportS3TargetDirective.class,
                        ImportDirective.DATA_POLICY_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public BlobStoreTaskPriority getPriority()
    {
        fetchBeanIfNull();
        return  m_bean.getPriority();
    }


    synchronized public S3TargetRM getTarget()
    {
        if ( null != m_bean )
        {
            return new S3TargetRM( m_bean.getTargetId(), m_serviceManager );
        }
        return new S3TargetRM(
                Require.exists( ImportS3TargetDirective.class,
                        ImportPublicCloudTargetDirective.TARGET_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public UserRM getUser()
    {
        if ( null != m_bean )
        {
            return new UserRM( m_bean.getUserId(), m_serviceManager );
        }
        return new UserRM(
                Require.exists( ImportS3TargetDirective.class,
                        ImportDirective.USER_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( ImportS3TargetDirective.class ).attain( m_whereClause );
        }
    }


    synchronized public ImportS3TargetDirective unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private ImportS3TargetDirective m_bean;
}
