/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.BlobStoreTaskPriority;
import com.spectralogic.s3.common.dao.domain.ds3.DataMigration;
import com.spectralogic.s3.common.dao.domain.ds3.DetailedAzureBlobDestination;
import com.spectralogic.s3.common.dao.domain.ds3.DetailedDs3BlobDestination;
import com.spectralogic.s3.common.dao.domain.ds3.DetailedJobEntry;
import com.spectralogic.s3.common.dao.domain.ds3.DetailedLocalBlobDestination;
import com.spectralogic.s3.common.dao.domain.ds3.DetailedS3BlobDestination;
import com.spectralogic.s3.common.dao.domain.ds3.Job;
import com.spectralogic.s3.common.dao.domain.ds3.JobChunkClientProcessingOrderGuarantee;
import com.spectralogic.s3.common.dao.domain.ds3.JobEntry;
import com.spectralogic.s3.common.dao.domain.ds3.JobObservable;
import com.spectralogic.s3.common.dao.domain.ds3.JobRequestType;
import com.spectralogic.s3.common.dao.domain.ds3.IomType;
import com.spectralogic.s3.common.dao.domain.ds3.UserIdObservable;
import com.spectralogic.s3.common.dao.domain.notification.JobCompletedNotificationRegistration;
import com.spectralogic.s3.common.dao.domain.notification.JobNotificationRegistrationObservable;
import com.spectralogic.s3.common.dao.domain.notification.S3ObjectCachedNotificationRegistration;
import com.spectralogic.s3.common.dao.domain.notification.S3ObjectPersistedNotificationRegistration;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import java.util.Date;
import java.util.UUID;


public class JobRM
{
    public JobRM( Job bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public JobRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    JobRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public boolean isAggregating()
    {
        fetchBeanIfNull();
        return  m_bean.isAggregating();
    }


    synchronized public BucketRM getBucket()
    {
        if ( null != m_bean )
        {
            return new BucketRM( m_bean.getBucketId(), m_serviceManager );
        }
        return new BucketRM(
                Require.exists( Job.class,
                        JobObservable.BUCKET_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public long getCachedSizeInBytes()
    {
        fetchBeanIfNull();
        return  m_bean.getCachedSizeInBytes();
    }


    synchronized public JobChunkClientProcessingOrderGuarantee getChunkClientProcessingOrderGuarantee()
    {
        fetchBeanIfNull();
        return  m_bean.getChunkClientProcessingOrderGuarantee();
    }


    synchronized public long getCompletedSizeInBytes()
    {
        fetchBeanIfNull();
        return  m_bean.getCompletedSizeInBytes();
    }


    synchronized public Date getCreatedAt()
    {
        fetchBeanIfNull();
        return  m_bean.getCreatedAt();
    }


    synchronized public boolean isDeadJobCleanupAllowed()
    {
        fetchBeanIfNull();
        return  m_bean.isDeadJobCleanupAllowed();
    }


    synchronized public String getErrorMessage()
    {
        fetchBeanIfNull();
        return  m_bean.getErrorMessage();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public boolean isImplicitJobIdResolution()
    {
        fetchBeanIfNull();
        return  m_bean.isImplicitJobIdResolution();
    }


   synchronized public RetrieveBeansResult< DetailedJobEntry > getDetailedJobEntries()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DetailedJobEntry.class ).retrieveAll(
            Require.beanPropertyEquals( JobEntry.JOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< S3ObjectPersistedNotificationRegistration > getS3ObjectPersistedNotificationRegistrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( S3ObjectPersistedNotificationRegistration.class ).retrieveAll(
            Require.beanPropertyEquals( JobNotificationRegistrationObservable.JOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< JobEntry > getJobEntries()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( JobEntry.class ).retrieveAll(
            Require.beanPropertyEquals( JobEntry.JOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< DetailedAzureBlobDestination > getDetailedAzureBlobDestinations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DetailedAzureBlobDestination.class ).retrieveAll(
            Require.beanPropertyEquals( DetailedAzureBlobDestination.JOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< JobCompletedNotificationRegistration > getJobCompletedNotificationRegistrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( JobCompletedNotificationRegistration.class ).retrieveAll(
            Require.beanPropertyEquals( JobNotificationRegistrationObservable.JOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< DetailedS3BlobDestination > getDetailedS3BlobDestinations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DetailedS3BlobDestination.class ).retrieveAll(
            Require.beanPropertyEquals( DetailedS3BlobDestination.JOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< DetailedDs3BlobDestination > getDetailedDs3BlobDestinations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DetailedDs3BlobDestination.class ).retrieveAll(
            Require.beanPropertyEquals( DetailedDs3BlobDestination.JOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< S3ObjectCachedNotificationRegistration > getS3ObjectCachedNotificationRegistrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( S3ObjectCachedNotificationRegistration.class ).retrieveAll(
            Require.beanPropertyEquals( JobNotificationRegistrationObservable.JOB_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< DetailedLocalBlobDestination > getDetailedLocalBlobDestinations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DetailedLocalBlobDestination.class ).retrieveAll(
            Require.beanPropertyEquals( DetailedLocalBlobDestination.JOB_ID, m_bean.getId() ) );
    }


    synchronized public boolean isMinimizeSpanningAcrossMedia()
    {
        fetchBeanIfNull();
        return  m_bean.isMinimizeSpanningAcrossMedia();
    }


    synchronized public boolean isNaked()
    {
        fetchBeanIfNull();
        return  m_bean.isNaked();
    }


    synchronized public String getName()
    {
        fetchBeanIfNull();
        return  m_bean.getName();
    }


    synchronized public long getOriginalSizeInBytes()
    {
        fetchBeanIfNull();
        return  m_bean.getOriginalSizeInBytes();
    }


    synchronized public BlobStoreTaskPriority getPriority()
    {
        fetchBeanIfNull();
        return  m_bean.getPriority();
    }


    synchronized public boolean isProtected()
    {
        fetchBeanIfNull();
        return  m_bean.isProtected();
    }


   synchronized public RetrieveBeansResult< DataMigration > getDataMigrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DataMigration.class ).retrieveAll(
            Require.beanPropertyEquals( DataMigration.PUT_JOB_ID, m_bean.getId() ) );
    }


    synchronized public Date getRechunked()
    {
        fetchBeanIfNull();
        return  m_bean.getRechunked();
    }


    synchronized public boolean isReplicating()
    {
        fetchBeanIfNull();
        return  m_bean.isReplicating();
    }


    synchronized public JobRequestType getRequestType()
    {
        fetchBeanIfNull();
        return  m_bean.getRequestType();
    }


    synchronized public IomType getRestore()
    {
        fetchBeanIfNull();
        return  m_bean.getIomType();
    }


    synchronized public boolean isTruncated()
    {
        fetchBeanIfNull();
        return  m_bean.isTruncated();
    }


    synchronized public boolean isTruncatedDueToTimeout()
    {
        fetchBeanIfNull();
        return  m_bean.isTruncatedDueToTimeout();
    }


    synchronized public UserRM getUser()
    {
        if ( null != m_bean )
        {
            return new UserRM( m_bean.getUserId(), m_serviceManager );
        }
        return new UserRM(
                Require.exists( Job.class,
                        UserIdObservable.USER_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public boolean isVerifyAfterWrite()
    {
        fetchBeanIfNull();
        return  m_bean.isVerifyAfterWrite();
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( Job.class ).attain( m_whereClause );
        }
    }


    synchronized public Job unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private Job m_bean;
}
