/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.DetailedJobEntry;
import com.spectralogic.s3.common.dao.domain.ds3.JobEntry;
import com.spectralogic.s3.common.dao.domain.ds3.Node;
import com.spectralogic.s3.common.dao.domain.planner.CacheFilesystem;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import java.util.Date;
import java.util.UUID;


public class NodeRM
{
    public NodeRM( Node bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public NodeRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    NodeRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public Integer getDataPathHttpsPort()
    {
        fetchBeanIfNull();
        return  m_bean.getDataPathHttpsPort();
    }


    synchronized public Integer getDataPathHttpPort()
    {
        fetchBeanIfNull();
        return  m_bean.getDataPathHttpPort();
    }


    synchronized public String getDataPathIpAddress()
    {
        fetchBeanIfNull();
        return  m_bean.getDataPathIpAddress();
    }


    synchronized public String getDnsName()
    {
        fetchBeanIfNull();
        return  m_bean.getDnsName();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public Date getLastHeartbeat()
    {
        fetchBeanIfNull();
        return  m_bean.getLastHeartbeat();
    }


    synchronized public String getName()
    {
        fetchBeanIfNull();
        return  m_bean.getName();
    }


   synchronized public RetrieveBeansResult< DetailedJobEntry > getDetailedJobEntries()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DetailedJobEntry.class ).retrieveAll(
            Require.beanPropertyEquals( JobEntry.NODE_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< CacheFilesystem > getCacheFilesystems()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( CacheFilesystem.class ).retrieveAll(
            Require.beanPropertyEquals( CacheFilesystem.NODE_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< JobEntry > getJobEntries()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( JobEntry.class ).retrieveAll(
            Require.beanPropertyEquals( JobEntry.NODE_ID, m_bean.getId() ) );
    }


    synchronized public String getSerialNumber()
    {
        fetchBeanIfNull();
        return  m_bean.getSerialNumber();
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( Node.class ).attain( m_whereClause );
        }
    }


    synchronized public Node unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private Node m_bean;
}
