/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.Obsoletion;
import com.spectralogic.s3.common.dao.domain.pool.ObsoleteBlobPool;
import com.spectralogic.s3.common.dao.domain.tape.ObsoleteBlobTape;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import java.util.Date;
import java.util.UUID;


public class ObsoletionRM
{
    public ObsoletionRM( Obsoletion bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public ObsoletionRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    ObsoletionRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public Date getDate()
    {
        fetchBeanIfNull();
        return  m_bean.getDate();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


   synchronized public RetrieveBeansResult< ObsoleteBlobTape > getObsoleteBlobTapes()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ObsoleteBlobTape.class ).retrieveAll(
            Require.beanPropertyEquals( ObsoleteBlobTape.OBSOLETION_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< ObsoleteBlobPool > getObsoleteBlobPools()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ObsoleteBlobPool.class ).retrieveAll(
            Require.beanPropertyEquals( ObsoleteBlobPool.OBSOLETION_ID, m_bean.getId() ) );
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( Obsoletion.class ).attain( m_whereClause );
        }
    }


    synchronized public Obsoletion unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private Obsoletion m_bean;
}
