/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.pool.BlobPool;
import com.spectralogic.s3.common.dao.domain.pool.ObsoleteBlobPool;
import com.spectralogic.s3.common.dao.domain.shared.BlobObservable;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import java.util.Date;
import java.util.UUID;


public class ObsoleteBlobPoolRM
{
    public ObsoleteBlobPoolRM( ObsoleteBlobPool bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public ObsoleteBlobPoolRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    ObsoleteBlobPoolRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public BlobRM getBlob()
    {
        if ( null != m_bean )
        {
            return new BlobRM( m_bean.getBlobId(), m_serviceManager );
        }
        return new BlobRM(
                Require.exists( ObsoleteBlobPool.class,
                        BlobObservable.BLOB_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public BucketRM getBucket()
    {
        if ( null != m_bean )
        {
            return new BucketRM( m_bean.getBucketId(), m_serviceManager );
        }
        return new BucketRM(
                Require.exists( ObsoleteBlobPool.class,
                        BlobPool.BUCKET_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public Date getDateWritten()
    {
        fetchBeanIfNull();
        return  m_bean.getDateWritten();
    }


    synchronized public BlobPoolRM get()
    {
        if ( null != m_bean )
        {
            return new BlobPoolRM( m_bean.getId(), m_serviceManager );
        }
        return new BlobPoolRM(
                Require.exists( ObsoleteBlobPool.class,
                        Identifiable.ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public Date getLastAccessed()
    {
        fetchBeanIfNull();
        return  m_bean.getLastAccessed();
    }


    synchronized public ObsoletionRM getObsoletion()
    {
        if ( null != m_bean )
        {
            return new ObsoletionRM( m_bean.getObsoletionId(), m_serviceManager );
        }
        return new ObsoletionRM(
                Require.exists( ObsoleteBlobPool.class,
                        ObsoleteBlobPool.OBSOLETION_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public PoolRM getPool()
    {
        if ( null != m_bean )
        {
            return new PoolRM( m_bean.getPoolId(), m_serviceManager );
        }
        return new PoolRM(
                Require.exists( ObsoleteBlobPool.class,
                        BlobPool.POOL_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( ObsoleteBlobPool.class ).attain( m_whereClause );
        }
    }


    synchronized public ObsoleteBlobPool unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private ObsoleteBlobPool m_bean;
}
