/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.DetailedJobEntry;
import com.spectralogic.s3.common.dao.domain.ds3.JobEntry;
import com.spectralogic.s3.common.dao.domain.pool.BlobPool;
import com.spectralogic.s3.common.dao.domain.pool.ImportPoolDirective;
import com.spectralogic.s3.common.dao.domain.pool.ObsoleteBlobPool;
import com.spectralogic.s3.common.dao.domain.pool.Pool;
import com.spectralogic.s3.common.dao.domain.pool.PoolFailure;
import com.spectralogic.s3.common.dao.domain.pool.PoolHealth;
import com.spectralogic.s3.common.dao.domain.pool.PoolState;
import com.spectralogic.s3.common.dao.domain.pool.PoolType;
import com.spectralogic.s3.common.dao.domain.pool.SuspectBlobPool;
import com.spectralogic.s3.common.dao.domain.shared.PersistenceTarget;
import com.spectralogic.s3.common.dao.domain.shared.Quiesced;
import com.spectralogic.s3.common.dao.domain.shared.ReadFromObservable;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import java.util.Date;
import java.util.UUID;


public class PoolRM
{
    public PoolRM( Pool bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public PoolRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    PoolRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public boolean isAssignedToStorageDomain()
    {
        fetchBeanIfNull();
        return  m_bean.isAssignedToStorageDomain();
    }


    synchronized public long getAvailableCapacity()
    {
        fetchBeanIfNull();
        return  m_bean.getAvailableCapacity();
    }


    synchronized public BucketRM getBucket()
    {
        if ( null != m_bean )
        {
            return new BucketRM( m_bean.getBucketId(), m_serviceManager );
        }
        return new BucketRM(
                Require.exists( Pool.class,
                        PersistenceTarget.BUCKET_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public String getGuid()
    {
        fetchBeanIfNull();
        return  m_bean.getGuid();
    }


    synchronized public PoolHealth getHealth()
    {
        fetchBeanIfNull();
        return  m_bean.getHealth();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public Date getLastAccessed()
    {
        fetchBeanIfNull();
        return  m_bean.getLastAccessed();
    }


    synchronized public Date getLastModified()
    {
        fetchBeanIfNull();
        return  m_bean.getLastModified();
    }


    synchronized public Date getLastVerified()
    {
        fetchBeanIfNull();
        return  m_bean.getLastVerified();
    }


    synchronized public String getMountpoint()
    {
        fetchBeanIfNull();
        return  m_bean.getMountpoint();
    }


    synchronized public String getName()
    {
        fetchBeanIfNull();
        return  m_bean.getName();
    }


    synchronized public PoolPartitionRM getPartition()
    {
        if ( null != m_bean )
        {
            return new PoolPartitionRM( m_bean.getPartitionId(), m_serviceManager );
        }
        return new PoolPartitionRM(
                Require.exists( Pool.class,
                        Pool.PARTITION_ID,
                        m_whereClause ),
                m_serviceManager );
    }


   synchronized public RetrieveBeansResult< PoolFailure > getPoolFailures()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( PoolFailure.class ).retrieveAll(
            Require.beanPropertyEquals( PoolFailure.POOL_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BlobPool > getBlobPools()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BlobPool.class ).retrieveAll(
            Require.beanPropertyEquals( BlobPool.POOL_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< SuspectBlobPool > getSuspectBlobPools()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( SuspectBlobPool.class ).retrieveAll(
            Require.beanPropertyEquals( BlobPool.POOL_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< ObsoleteBlobPool > getObsoleteBlobPools()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ObsoleteBlobPool.class ).retrieveAll(
            Require.beanPropertyEquals( BlobPool.POOL_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< ImportPoolDirective > getImportPoolDirectives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ImportPoolDirective.class ).retrieveAll(
            Require.beanPropertyEquals( ImportPoolDirective.POOL_ID, m_bean.getId() ) );
    }


    synchronized public boolean isPoweredOn()
    {
        fetchBeanIfNull();
        return  m_bean.isPoweredOn();
    }


    synchronized public Quiesced getQuiesced()
    {
        fetchBeanIfNull();
        return  m_bean.getQuiesced();
    }


   synchronized public RetrieveBeansResult< DetailedJobEntry > getDetailedJobEntries()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DetailedJobEntry.class ).retrieveAll(
            Require.beanPropertyEquals( ReadFromObservable.READ_FROM_POOL_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< JobEntry > getJobEntries()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( JobEntry.class ).retrieveAll(
            Require.beanPropertyEquals( ReadFromObservable.READ_FROM_POOL_ID, m_bean.getId() ) );
    }


    synchronized public long getReservedCapacity()
    {
        fetchBeanIfNull();
        return  m_bean.getReservedCapacity();
    }


    synchronized public PoolState getState()
    {
        fetchBeanIfNull();
        return  m_bean.getState();
    }


    synchronized public StorageDomainMemberRM getStorageDomainMember()
    {
        if ( null != m_bean )
        {
            return new StorageDomainMemberRM( m_bean.getStorageDomainMemberId(), m_serviceManager );
        }
        return new StorageDomainMemberRM(
                Require.exists( Pool.class,
                        PersistenceTarget.STORAGE_DOMAIN_MEMBER_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public long getTotalCapacity()
    {
        fetchBeanIfNull();
        return  m_bean.getTotalCapacity();
    }


    synchronized public PoolType getType()
    {
        fetchBeanIfNull();
        return  m_bean.getType();
    }


    synchronized public long getUsedCapacity()
    {
        fetchBeanIfNull();
        return  m_bean.getUsedCapacity();
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( Pool.class ).attain( m_whereClause );
        }
    }


    synchronized public Pool unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private Pool m_bean;
}
