/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.BlobStoreTaskPriority;
import com.spectralogic.s3.common.dao.domain.shared.ImportDirective;
import com.spectralogic.s3.common.dao.domain.shared.ImportPersistenceTargetDirective;
import com.spectralogic.s3.common.dao.domain.shared.ImportTapeTargetDirective;
import com.spectralogic.s3.common.dao.domain.tape.RawImportTapeDirective;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import java.util.UUID;


public class RawImportTapeDirectiveRM
{
    public RawImportTapeDirectiveRM( RawImportTapeDirective bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public RawImportTapeDirectiveRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    RawImportTapeDirectiveRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public BucketRM getBucket()
    {
        if ( null != m_bean )
        {
            return new BucketRM( m_bean.getBucketId(), m_serviceManager );
        }
        return new BucketRM(
                Require.exists( RawImportTapeDirective.class,
                        RawImportTapeDirective.BUCKET_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public DataPolicyRM getDataPolicy()
    {
        if ( null != m_bean )
        {
            return new DataPolicyRM( m_bean.getDataPolicyId(), m_serviceManager );
        }
        return new DataPolicyRM(
                Require.exists( RawImportTapeDirective.class,
                        ImportDirective.DATA_POLICY_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public StorageDomainRM getStorageDomain()
    {
        if ( null != m_bean )
        {
            return new StorageDomainRM( m_bean.getStorageDomainId(), m_serviceManager );
        }
        return new StorageDomainRM(
                Require.exists( RawImportTapeDirective.class,
                        ImportPersistenceTargetDirective.STORAGE_DOMAIN_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public TapeRM getTape()
    {
        if ( null != m_bean )
        {
            return new TapeRM( m_bean.getTapeId(), m_serviceManager );
        }
        return new TapeRM(
                Require.exists( RawImportTapeDirective.class,
                        ImportTapeTargetDirective.TAPE_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public UserRM getUser()
    {
        if ( null != m_bean )
        {
            return new UserRM( m_bean.getUserId(), m_serviceManager );
        }
        return new UserRM(
                Require.exists( RawImportTapeDirective.class,
                        ImportDirective.USER_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public BlobStoreTaskPriority getVerifyDataAfterImport()
    {
        fetchBeanIfNull();
        return  m_bean.getVerifyDataAfterImport();
    }


    synchronized public boolean isVerifyDataPriorToImport()
    {
        fetchBeanIfNull();
        return  m_bean.isVerifyDataPriorToImport();
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( RawImportTapeDirective.class ).attain( m_whereClause );
        }
    }


    synchronized public RawImportTapeDirective unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private RawImportTapeDirective m_bean;
}
