/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.Blob;
import com.spectralogic.s3.common.dao.domain.ds3.DetailedJobEntry;
import com.spectralogic.s3.common.dao.domain.ds3.S3Object;
import com.spectralogic.s3.common.dao.domain.ds3.S3ObjectProperty;
import com.spectralogic.s3.common.dao.domain.ds3.S3ObjectType;
import com.spectralogic.s3.common.dao.domain.target.S3MultipartUpload;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import java.util.Date;
import java.util.UUID;


public class S3ObjectRM
{
    public S3ObjectRM( S3Object bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public S3ObjectRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    S3ObjectRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public BucketRM getBucket()
    {
        if ( null != m_bean )
        {
            return new BucketRM( m_bean.getBucketId(), m_serviceManager );
        }
        return new BucketRM(
                Require.exists( S3Object.class,
                        S3Object.BUCKET_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public Date getCreationDate()
    {
        fetchBeanIfNull();
        return  m_bean.getCreationDate();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public boolean isLatest()
    {
        fetchBeanIfNull();
        return  m_bean.isLatest();
    }


    synchronized public String getName()
    {
        fetchBeanIfNull();
        return  m_bean.getName();
    }


   synchronized public RetrieveBeansResult< DetailedJobEntry > getDetailedJobEntries()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DetailedJobEntry.class ).retrieveAll(
            Require.beanPropertyEquals( DetailedJobEntry.OBJECT_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< S3MultipartUpload > getS3MultipartUploads()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( S3MultipartUpload.class ).retrieveAll(
            Require.beanPropertyEquals( S3MultipartUpload.OBJECT_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< Blob > getBlobs()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( Blob.class ).retrieveAll(
            Require.beanPropertyEquals( Blob.OBJECT_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< S3ObjectProperty > getS3ObjectProperties()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( S3ObjectProperty.class ).retrieveAll(
            Require.beanPropertyEquals( S3ObjectProperty.OBJECT_ID, m_bean.getId() ) );
    }


    synchronized public S3ObjectType getType()
    {
        fetchBeanIfNull();
        return  m_bean.getType();
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( S3Object.class ).attain( m_whereClause );
        }
    }


    synchronized public S3Object unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private S3Object m_bean;
}
