/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.S3ObjectProperty;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import java.util.UUID;


public class S3ObjectPropertyRM
{
    public S3ObjectPropertyRM( S3ObjectProperty bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public S3ObjectPropertyRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    S3ObjectPropertyRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public String getKey()
    {
        fetchBeanIfNull();
        return  m_bean.getKey();
    }


    synchronized public S3ObjectRM getObject()
    {
        if ( null != m_bean )
        {
            return new S3ObjectRM( m_bean.getObjectId(), m_serviceManager );
        }
        return new S3ObjectRM(
                Require.exists( S3ObjectProperty.class,
                        S3ObjectProperty.OBJECT_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public String getValue()
    {
        fetchBeanIfNull();
        return  m_bean.getValue();
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( S3ObjectProperty.class ).attain( m_whereClause );
        }
    }


    synchronized public S3ObjectProperty unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private S3ObjectProperty m_bean;
}
