/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.CloudNamingMode;
import com.spectralogic.s3.common.dao.domain.ds3.DataReplicationRule;
import com.spectralogic.s3.common.dao.domain.ds3.DetailedJobEntry;
import com.spectralogic.s3.common.dao.domain.ds3.DetailedS3BlobDestination;
import com.spectralogic.s3.common.dao.domain.ds3.JobEntry;
import com.spectralogic.s3.common.dao.domain.ds3.RemoteBlobDestination;
import com.spectralogic.s3.common.dao.domain.ds3.S3BlobDestination;
import com.spectralogic.s3.common.dao.domain.ds3.S3DataReplicationRule;
import com.spectralogic.s3.common.dao.domain.ds3.S3Region;
import com.spectralogic.s3.common.dao.domain.shared.ImportPublicCloudTargetDirective;
import com.spectralogic.s3.common.dao.domain.shared.Quiesced;
import com.spectralogic.s3.common.dao.domain.shared.ReadFromObservable;
import com.spectralogic.s3.common.dao.domain.target.BlobS3Target;
import com.spectralogic.s3.common.dao.domain.target.BlobTarget;
import com.spectralogic.s3.common.dao.domain.target.ImportS3TargetDirective;
import com.spectralogic.s3.common.dao.domain.target.PublicCloudTargetBucketName;
import com.spectralogic.s3.common.dao.domain.target.S3Target;
import com.spectralogic.s3.common.dao.domain.target.S3TargetBucketName;
import com.spectralogic.s3.common.dao.domain.target.S3TargetFailure;
import com.spectralogic.s3.common.dao.domain.target.S3TargetReadPreference;
import com.spectralogic.s3.common.dao.domain.target.SuspectBlobS3Target;
import com.spectralogic.s3.common.dao.domain.target.TargetFailure;
import com.spectralogic.s3.common.dao.domain.target.TargetReadPreference;
import com.spectralogic.s3.common.dao.domain.target.TargetReadPreferenceType;
import com.spectralogic.s3.common.dao.domain.target.TargetState;
import com.spectralogic.s3.common.dao.domain.temp.BlobS3TargetToVerify;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import java.util.Date;
import java.util.UUID;


public class S3TargetRM
{
    public S3TargetRM( S3Target bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public S3TargetRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    S3TargetRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public String getAccessKey()
    {
        fetchBeanIfNull();
        return  m_bean.getAccessKey();
    }


    synchronized public Integer getAutoVerifyFrequencyInDays()
    {
        fetchBeanIfNull();
        return  m_bean.getAutoVerifyFrequencyInDays();
    }


    synchronized public String getCloudBucketPrefix()
    {
        fetchBeanIfNull();
        return  m_bean.getCloudBucketPrefix();
    }


    synchronized public String getCloudBucketSuffix()
    {
        fetchBeanIfNull();
        return  m_bean.getCloudBucketSuffix();
    }


    synchronized public String getDataPathEndPoint()
    {
        fetchBeanIfNull();
        return  m_bean.getDataPathEndPoint();
    }


    synchronized public TargetReadPreferenceType getDefaultReadPreference()
    {
        fetchBeanIfNull();
        return  m_bean.getDefaultReadPreference();
    }


    synchronized public boolean isHttps()
    {
        fetchBeanIfNull();
        return  m_bean.isHttps();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public Date getLastFullyVerified()
    {
        fetchBeanIfNull();
        return  m_bean.getLastFullyVerified();
    }


    synchronized public String getName()
    {
        fetchBeanIfNull();
        return  m_bean.getName();
    }


    synchronized public CloudNamingMode getNamingMode()
    {
        fetchBeanIfNull();
        return  m_bean.getNamingMode();
    }


    synchronized public int getOfflineDataStagingWindowInTb()
    {
        fetchBeanIfNull();
        return  m_bean.getOfflineDataStagingWindowInTb();
    }


    synchronized public boolean isPermitGoingOutOfSync()
    {
        fetchBeanIfNull();
        return  m_bean.isPermitGoingOutOfSync();
    }


    synchronized public String getProxyDomain()
    {
        fetchBeanIfNull();
        return  m_bean.getProxyDomain();
    }


    synchronized public String getProxyHost()
    {
        fetchBeanIfNull();
        return  m_bean.getProxyHost();
    }


    synchronized public String getProxyPassword()
    {
        fetchBeanIfNull();
        return  m_bean.getProxyPassword();
    }


    synchronized public Integer getProxyPort()
    {
        fetchBeanIfNull();
        return  m_bean.getProxyPort();
    }


    synchronized public String getProxyUsername()
    {
        fetchBeanIfNull();
        return  m_bean.getProxyUsername();
    }


    synchronized public Quiesced getQuiesced()
    {
        fetchBeanIfNull();
        return  m_bean.getQuiesced();
    }


   synchronized public RetrieveBeansResult< DetailedJobEntry > getDetailedJobEntries()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DetailedJobEntry.class ).retrieveAll(
            Require.beanPropertyEquals( ReadFromObservable.READ_FROM_S3_TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< JobEntry > getJobEntries()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( JobEntry.class ).retrieveAll(
            Require.beanPropertyEquals( ReadFromObservable.READ_FROM_S3_TARGET_ID, m_bean.getId() ) );
    }


    synchronized public S3Region getRegion()
    {
        fetchBeanIfNull();
        return  m_bean.getRegion();
    }


    synchronized public boolean isRestrictedAccess()
    {
        fetchBeanIfNull();
        return  m_bean.isRestrictedAccess();
    }


    synchronized public String getSecretKey()
    {
        fetchBeanIfNull();
        return  m_bean.getSecretKey();
    }


    synchronized public int getStagedDataExpirationInDays()
    {
        fetchBeanIfNull();
        return  m_bean.getStagedDataExpirationInDays();
    }


    synchronized public TargetState getState()
    {
        fetchBeanIfNull();
        return  m_bean.getState();
    }


   synchronized public RetrieveBeansResult< S3DataReplicationRule > getS3DataReplicationRules()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( S3DataReplicationRule.class ).retrieveAll(
            Require.beanPropertyEquals( DataReplicationRule.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BlobS3Target > getBlobS3Targets()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BlobS3Target.class ).retrieveAll(
            Require.beanPropertyEquals( BlobTarget.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< DetailedS3BlobDestination > getDetailedS3BlobDestinations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DetailedS3BlobDestination.class ).retrieveAll(
            Require.beanPropertyEquals( RemoteBlobDestination.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< S3TargetBucketName > getS3TargetBucketNames()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( S3TargetBucketName.class ).retrieveAll(
            Require.beanPropertyEquals( PublicCloudTargetBucketName.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< S3TargetFailure > getS3TargetFailures()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( S3TargetFailure.class ).retrieveAll(
            Require.beanPropertyEquals( TargetFailure.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< S3TargetReadPreference > getS3TargetReadPreferences()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( S3TargetReadPreference.class ).retrieveAll(
            Require.beanPropertyEquals( TargetReadPreference.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< SuspectBlobS3Target > getSuspectBlobS3Targets()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( SuspectBlobS3Target.class ).retrieveAll(
            Require.beanPropertyEquals( BlobTarget.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BlobS3TargetToVerify > getBlobS3TargetToVerifies()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BlobS3TargetToVerify.class ).retrieveAll(
            Require.beanPropertyEquals( BlobTarget.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< ImportS3TargetDirective > getImportS3TargetDirectives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ImportS3TargetDirective.class ).retrieveAll(
            Require.beanPropertyEquals( ImportPublicCloudTargetDirective.TARGET_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< S3BlobDestination > getS3BlobDestinations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( S3BlobDestination.class ).retrieveAll(
            Require.beanPropertyEquals( RemoteBlobDestination.TARGET_ID, m_bean.getId() ) );
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( S3Target.class ).attain( m_whereClause );
        }
    }


    synchronized public S3Target unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private S3Target m_bean;
}
