/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.BlobStoreTaskPriority;
import com.spectralogic.s3.common.dao.domain.ds3.DataPersistenceRule;
import com.spectralogic.s3.common.dao.domain.ds3.DetailedLocalBlobDestination;
import com.spectralogic.s3.common.dao.domain.ds3.LocalBlobDestination;
import com.spectralogic.s3.common.dao.domain.ds3.LtfsFileNamingMode;
import com.spectralogic.s3.common.dao.domain.ds3.StorageDomain;
import com.spectralogic.s3.common.dao.domain.ds3.StorageDomainFailure;
import com.spectralogic.s3.common.dao.domain.ds3.StorageDomainMember;
import com.spectralogic.s3.common.dao.domain.ds3.WriteOptimization;
import com.spectralogic.s3.common.dao.domain.pool.ImportPoolDirective;
import com.spectralogic.s3.common.dao.domain.shared.ImportPersistenceTargetDirective;
import com.spectralogic.s3.common.dao.domain.tape.ImportTapeDirective;
import com.spectralogic.s3.common.dao.domain.tape.RawImportTapeDirective;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import java.util.UUID;


public class StorageDomainRM
{
    public StorageDomainRM( StorageDomain bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public StorageDomainRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    StorageDomainRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public Long getAutoEjectMediaFullThreshold()
    {
        fetchBeanIfNull();
        return  m_bean.getAutoEjectMediaFullThreshold();
    }


    synchronized public String getAutoEjectUponCron()
    {
        fetchBeanIfNull();
        return  m_bean.getAutoEjectUponCron();
    }


    synchronized public boolean isAutoEjectUponJobCancellation()
    {
        fetchBeanIfNull();
        return  m_bean.isAutoEjectUponJobCancellation();
    }


    synchronized public boolean isAutoEjectUponJobCompletion()
    {
        fetchBeanIfNull();
        return  m_bean.isAutoEjectUponJobCompletion();
    }


    synchronized public boolean isAutoEjectUponMediaFull()
    {
        fetchBeanIfNull();
        return  m_bean.isAutoEjectUponMediaFull();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public LtfsFileNamingMode getLtfsFileNaming()
    {
        fetchBeanIfNull();
        return  m_bean.getLtfsFileNaming();
    }


    synchronized public Integer getMaximumAutoVerificationFrequencyInDays()
    {
        fetchBeanIfNull();
        return  m_bean.getMaximumAutoVerificationFrequencyInDays();
    }


    synchronized public int getMaxTapeFragmentationPercent()
    {
        fetchBeanIfNull();
        return  m_bean.getMaxTapeFragmentationPercent();
    }


    synchronized public boolean isMediaEjectionAllowed()
    {
        fetchBeanIfNull();
        return  m_bean.isMediaEjectionAllowed();
    }


    synchronized public String getName()
    {
        fetchBeanIfNull();
        return  m_bean.getName();
    }


    synchronized public boolean isSecureMediaAllocation()
    {
        fetchBeanIfNull();
        return  m_bean.isSecureMediaAllocation();
    }


   synchronized public RetrieveBeansResult< ImportTapeDirective > getImportTapeDirectives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ImportTapeDirective.class ).retrieveAll(
            Require.beanPropertyEquals( ImportPersistenceTargetDirective.STORAGE_DOMAIN_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< StorageDomainMember > getStorageDomainMembers()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( StorageDomainMember.class ).retrieveAll(
            Require.beanPropertyEquals( StorageDomainMember.STORAGE_DOMAIN_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< RawImportTapeDirective > getRawImportTapeDirectives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( RawImportTapeDirective.class ).retrieveAll(
            Require.beanPropertyEquals( ImportPersistenceTargetDirective.STORAGE_DOMAIN_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< LocalBlobDestination > getLocalBlobDestinations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( LocalBlobDestination.class ).retrieveAll(
            Require.beanPropertyEquals( LocalBlobDestination.STORAGE_DOMAIN_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< StorageDomainFailure > getStorageDomainFailures()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( StorageDomainFailure.class ).retrieveAll(
            Require.beanPropertyEquals( StorageDomainFailure.STORAGE_DOMAIN_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< DetailedLocalBlobDestination > getDetailedLocalBlobDestinations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DetailedLocalBlobDestination.class ).retrieveAll(
            Require.beanPropertyEquals( LocalBlobDestination.STORAGE_DOMAIN_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< DataPersistenceRule > getDataPersistenceRules()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DataPersistenceRule.class ).retrieveAll(
            Require.beanPropertyEquals( DataPersistenceRule.STORAGE_DOMAIN_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< ImportPoolDirective > getImportPoolDirectives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ImportPoolDirective.class ).retrieveAll(
            Require.beanPropertyEquals( ImportPersistenceTargetDirective.STORAGE_DOMAIN_ID, m_bean.getId() ) );
    }


    synchronized public BlobStoreTaskPriority getVerifyPriorToAutoEject()
    {
        fetchBeanIfNull();
        return  m_bean.getVerifyPriorToAutoEject();
    }


    synchronized public WriteOptimization getWriteOptimization()
    {
        fetchBeanIfNull();
        return  m_bean.getWriteOptimization();
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( StorageDomain.class ).attain( m_whereClause );
        }
    }


    synchronized public StorageDomain unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private StorageDomain m_bean;
}
