/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.StorageDomainMember;
import com.spectralogic.s3.common.dao.domain.ds3.StorageDomainMemberState;
import com.spectralogic.s3.common.dao.domain.ds3.WritePreferenceLevel;
import com.spectralogic.s3.common.dao.domain.pool.Pool;
import com.spectralogic.s3.common.dao.domain.shared.PersistenceTarget;
import com.spectralogic.s3.common.dao.domain.tape.Tape;
import com.spectralogic.s3.common.dao.domain.tape.TapeType;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import java.util.UUID;


public class StorageDomainMemberRM
{
    public StorageDomainMemberRM( StorageDomainMember bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public StorageDomainMemberRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    StorageDomainMemberRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public Integer getAutoCompactionThreshold()
    {
        fetchBeanIfNull();
        return  m_bean.getAutoCompactionThreshold();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public PoolPartitionRM getPoolPartition()
    {
        if ( null != m_bean )
        {
            return new PoolPartitionRM( m_bean.getPoolPartitionId(), m_serviceManager );
        }
        return new PoolPartitionRM(
                Require.exists( StorageDomainMember.class,
                        StorageDomainMember.POOL_PARTITION_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public StorageDomainMemberState getState()
    {
        fetchBeanIfNull();
        return  m_bean.getState();
    }


    synchronized public StorageDomainRM getStorageDomain()
    {
        if ( null != m_bean )
        {
            return new StorageDomainRM( m_bean.getStorageDomainId(), m_serviceManager );
        }
        return new StorageDomainRM(
                Require.exists( StorageDomainMember.class,
                        StorageDomainMember.STORAGE_DOMAIN_ID,
                        m_whereClause ),
                m_serviceManager );
    }


   synchronized public RetrieveBeansResult< Tape > getTapes()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( Tape.class ).retrieveAll(
            Require.beanPropertyEquals( PersistenceTarget.STORAGE_DOMAIN_MEMBER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< Pool > getPools()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( Pool.class ).retrieveAll(
            Require.beanPropertyEquals( PersistenceTarget.STORAGE_DOMAIN_MEMBER_ID, m_bean.getId() ) );
    }


    synchronized public TapePartitionRM getTapePartition()
    {
        if ( null != m_bean )
        {
            return new TapePartitionRM( m_bean.getTapePartitionId(), m_serviceManager );
        }
        return new TapePartitionRM(
                Require.exists( StorageDomainMember.class,
                        StorageDomainMember.TAPE_PARTITION_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public TapeType getTapeType()
    {
        fetchBeanIfNull();
        return  m_bean.getTapeType();
    }


    synchronized public WritePreferenceLevel getWritePreference()
    {
        fetchBeanIfNull();
        return  m_bean.getWritePreference();
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( StorageDomainMember.class ).attain( m_whereClause );
        }
    }


    synchronized public StorageDomainMember unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private StorageDomainMember m_bean;
}
