/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.shared.BlobObservable;
import com.spectralogic.s3.common.dao.domain.target.BlobTarget;
import com.spectralogic.s3.common.dao.domain.target.SuspectBlobDs3Target;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import java.util.UUID;


public class SuspectBlobDs3TargetRM
{
    public SuspectBlobDs3TargetRM( SuspectBlobDs3Target bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public SuspectBlobDs3TargetRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    SuspectBlobDs3TargetRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public BlobRM getBlob()
    {
        if ( null != m_bean )
        {
            return new BlobRM( m_bean.getBlobId(), m_serviceManager );
        }
        return new BlobRM(
                Require.exists( SuspectBlobDs3Target.class,
                        BlobObservable.BLOB_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public BlobDs3TargetRM get()
    {
        if ( null != m_bean )
        {
            return new BlobDs3TargetRM( m_bean.getId(), m_serviceManager );
        }
        return new BlobDs3TargetRM(
                Require.exists( SuspectBlobDs3Target.class,
                        Identifiable.ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public Ds3TargetRM getTarget()
    {
        if ( null != m_bean )
        {
            return new Ds3TargetRM( m_bean.getTargetId(), m_serviceManager );
        }
        return new Ds3TargetRM(
                Require.exists( SuspectBlobDs3Target.class,
                        BlobTarget.TARGET_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( SuspectBlobDs3Target.class ).attain( m_whereClause );
        }
    }


    synchronized public SuspectBlobDs3Target unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private SuspectBlobDs3Target m_bean;
}
