/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.shared.BlobObservable;
import com.spectralogic.s3.common.dao.domain.tape.BlobTape;
import com.spectralogic.s3.common.dao.domain.tape.SuspectBlobTape;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import java.util.UUID;


public class SuspectBlobTapeRM
{
    public SuspectBlobTapeRM( SuspectBlobTape bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public SuspectBlobTapeRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    SuspectBlobTapeRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public BlobRM getBlob()
    {
        if ( null != m_bean )
        {
            return new BlobRM( m_bean.getBlobId(), m_serviceManager );
        }
        return new BlobRM(
                Require.exists( SuspectBlobTape.class,
                        BlobObservable.BLOB_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public BlobTapeRM get()
    {
        if ( null != m_bean )
        {
            return new BlobTapeRM( m_bean.getId(), m_serviceManager );
        }
        return new BlobTapeRM(
                Require.exists( SuspectBlobTape.class,
                        Identifiable.ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public int getOrderIndex()
    {
        fetchBeanIfNull();
        return  m_bean.getOrderIndex();
    }


    synchronized public TapeRM getTape()
    {
        if ( null != m_bean )
        {
            return new TapeRM( m_bean.getTapeId(), m_serviceManager );
        }
        return new TapeRM(
                Require.exists( SuspectBlobTape.class,
                        BlobTape.TAPE_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( SuspectBlobTape.class ).attain( m_whereClause );
        }
    }


    synchronized public SuspectBlobTape unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private SuspectBlobTape m_bean;
}
