/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.BlobStoreTaskPriority;
import com.spectralogic.s3.common.dao.domain.ds3.DetailedJobEntry;
import com.spectralogic.s3.common.dao.domain.ds3.JobEntry;
import com.spectralogic.s3.common.dao.domain.shared.ImportTapeTargetDirective;
import com.spectralogic.s3.common.dao.domain.shared.PersistenceTarget;
import com.spectralogic.s3.common.dao.domain.shared.ReadFromObservable;
import com.spectralogic.s3.common.dao.domain.tape.BlobTape;
import com.spectralogic.s3.common.dao.domain.tape.ImportTapeDirective;
import com.spectralogic.s3.common.dao.domain.tape.ObsoleteBlobTape;
import com.spectralogic.s3.common.dao.domain.tape.RawImportTapeDirective;
import com.spectralogic.s3.common.dao.domain.tape.SuspectBlobTape;
import com.spectralogic.s3.common.dao.domain.tape.Tape;
import com.spectralogic.s3.common.dao.domain.tape.TapeDrive;
import com.spectralogic.s3.common.dao.domain.tape.TapeFailure;
import com.spectralogic.s3.common.dao.domain.tape.TapeRole;
import com.spectralogic.s3.common.dao.domain.tape.TapeState;
import com.spectralogic.s3.common.dao.domain.tape.TapeType;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import java.util.Date;
import java.util.UUID;


public class TapeRM
{
    public TapeRM( Tape bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public TapeRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    TapeRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public boolean isAllowRollback()
    {
        fetchBeanIfNull();
        return  m_bean.isAllowRollback();
    }


    synchronized public boolean isAssignedToStorageDomain()
    {
        fetchBeanIfNull();
        return  m_bean.isAssignedToStorageDomain();
    }


    synchronized public Long getAvailableRawCapacity()
    {
        fetchBeanIfNull();
        return  m_bean.getAvailableRawCapacity();
    }


    synchronized public String getBarCode()
    {
        fetchBeanIfNull();
        return  m_bean.getBarCode();
    }


    synchronized public BucketRM getBucket()
    {
        if ( null != m_bean )
        {
            return new BucketRM( m_bean.getBucketId(), m_serviceManager );
        }
        return new BucketRM(
                Require.exists( Tape.class,
                        PersistenceTarget.BUCKET_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public String getDescriptionForIdentification()
    {
        fetchBeanIfNull();
        return  m_bean.getDescriptionForIdentification();
    }


    synchronized public Date getEjectDate()
    {
        fetchBeanIfNull();
        return  m_bean.getEjectDate();
    }


    synchronized public String getEjectLabel()
    {
        fetchBeanIfNull();
        return  m_bean.getEjectLabel();
    }


    synchronized public String getEjectLocation()
    {
        fetchBeanIfNull();
        return  m_bean.getEjectLocation();
    }


    synchronized public Date getEjectPending()
    {
        fetchBeanIfNull();
        return  m_bean.getEjectPending();
    }


    synchronized public boolean isFullOfData()
    {
        fetchBeanIfNull();
        return  m_bean.isFullOfData();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public Date getLastAccessed()
    {
        fetchBeanIfNull();
        return  m_bean.getLastAccessed();
    }


    synchronized public String getLastCheckpoint()
    {
        fetchBeanIfNull();
        return  m_bean.getLastCheckpoint();
    }


    synchronized public Date getLastModified()
    {
        fetchBeanIfNull();
        return  m_bean.getLastModified();
    }


    synchronized public Date getLastVerified()
    {
        fetchBeanIfNull();
        return  m_bean.getLastVerified();
    }


    synchronized public Date getPartiallyVerifiedEndOfTape()
    {
        fetchBeanIfNull();
        return  m_bean.getPartiallyVerifiedEndOfTape();
    }


    synchronized public TapePartitionRM getPartition()
    {
        if ( null != m_bean )
        {
            return new TapePartitionRM( m_bean.getPartitionId(), m_serviceManager );
        }
        return new TapePartitionRM(
                Require.exists( Tape.class,
                        Tape.PARTITION_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public TapeState getPreviousState()
    {
        fetchBeanIfNull();
        return  m_bean.getPreviousState();
    }


   synchronized public RetrieveBeansResult< DetailedJobEntry > getDetailedJobEntries()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DetailedJobEntry.class ).retrieveAll(
            Require.beanPropertyEquals( ReadFromObservable.READ_FROM_TAPE_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< JobEntry > getJobEntries()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( JobEntry.class ).retrieveAll(
            Require.beanPropertyEquals( ReadFromObservable.READ_FROM_TAPE_ID, m_bean.getId() ) );
    }


    synchronized public TapeRole getRole()
    {
        fetchBeanIfNull();
        return  m_bean.getRole();
    }


    synchronized public String getSerialNumber()
    {
        fetchBeanIfNull();
        return  m_bean.getSerialNumber();
    }


    synchronized public TapeState getState()
    {
        fetchBeanIfNull();
        return  m_bean.getState();
    }


    synchronized public StorageDomainMemberRM getStorageDomainMember()
    {
        if ( null != m_bean )
        {
            return new StorageDomainMemberRM( m_bean.getStorageDomainMemberId(), m_serviceManager );
        }
        return new StorageDomainMemberRM(
                Require.exists( Tape.class,
                        PersistenceTarget.STORAGE_DOMAIN_MEMBER_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public boolean isTakeOwnershipPending()
    {
        fetchBeanIfNull();
        return  m_bean.isTakeOwnershipPending();
    }


   synchronized public RetrieveBeansResult< ImportTapeDirective > getImportTapeDirectives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ImportTapeDirective.class ).retrieveAll(
            Require.beanPropertyEquals( ImportTapeTargetDirective.TAPE_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< RawImportTapeDirective > getRawImportTapeDirectives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( RawImportTapeDirective.class ).retrieveAll(
            Require.beanPropertyEquals( ImportTapeTargetDirective.TAPE_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< TapeDrive > getTapeDrives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( TapeDrive.class ).retrieveAll(
            Require.beanPropertyEquals( TapeDrive.TAPE_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< TapeFailure > getTapeFailures()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( TapeFailure.class ).retrieveAll(
            Require.beanPropertyEquals( TapeFailure.TAPE_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< ObsoleteBlobTape > getObsoleteBlobTapes()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ObsoleteBlobTape.class ).retrieveAll(
            Require.beanPropertyEquals( BlobTape.TAPE_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BlobTape > getBlobTapes()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BlobTape.class ).retrieveAll(
            Require.beanPropertyEquals( BlobTape.TAPE_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< SuspectBlobTape > getSuspectBlobTapes()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( SuspectBlobTape.class ).retrieveAll(
            Require.beanPropertyEquals( BlobTape.TAPE_ID, m_bean.getId() ) );
    }


    synchronized public Long getTotalRawCapacity()
    {
        fetchBeanIfNull();
        return  m_bean.getTotalRawCapacity();
    }


    synchronized public TapeType getType()
    {
        fetchBeanIfNull();
        return  m_bean.getType();
    }


    synchronized public BlobStoreTaskPriority getVerifyPending()
    {
        fetchBeanIfNull();
        return  m_bean.getVerifyPending();
    }


    synchronized public boolean isWriteProtected()
    {
        fetchBeanIfNull();
        return  m_bean.isWriteProtected();
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( Tape.class ).attain( m_whereClause );
        }
    }


    synchronized public Tape unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private Tape m_bean;
}
