/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.StorageDomainMember;
import com.spectralogic.s3.common.dao.domain.shared.Quiesced;
import com.spectralogic.s3.common.dao.domain.tape.ImportExportConfiguration;
import com.spectralogic.s3.common.dao.domain.tape.Tape;
import com.spectralogic.s3.common.dao.domain.tape.TapeDensityDirective;
import com.spectralogic.s3.common.dao.domain.tape.TapeDrive;
import com.spectralogic.s3.common.dao.domain.tape.TapeDriveType;
import com.spectralogic.s3.common.dao.domain.tape.TapePartition;
import com.spectralogic.s3.common.dao.domain.tape.TapePartitionFailure;
import com.spectralogic.s3.common.dao.domain.tape.TapePartitionState;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import java.util.UUID;


public class TapePartitionRM
{
    public TapePartitionRM( TapePartition bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public TapePartitionRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    TapePartitionRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public boolean isAutoCompactionEnabled()
    {
        fetchBeanIfNull();
        return  m_bean.isAutoCompactionEnabled();
    }


    synchronized public boolean isAutoQuiesceEnabled()
    {
        fetchBeanIfNull();
        return  m_bean.isAutoQuiesceEnabled();
    }


    synchronized public Integer getDriveIdleTimeoutInMinutes()
    {
        fetchBeanIfNull();
        return  m_bean.getDriveIdleTimeoutInMinutes();
    }


    synchronized public TapeDriveType getDriveType()
    {
        fetchBeanIfNull();
        return  m_bean.getDriveType();
    }


    synchronized public String getErrorMessage()
    {
        fetchBeanIfNull();
        return  m_bean.getErrorMessage();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public ImportExportConfiguration getImportExportConfiguration()
    {
        fetchBeanIfNull();
        return  m_bean.getImportExportConfiguration();
    }


    synchronized public TapeLibraryRM getLibrary()
    {
        if ( null != m_bean )
        {
            return new TapeLibraryRM( m_bean.getLibraryId(), m_serviceManager );
        }
        return new TapeLibraryRM(
                Require.exists( TapePartition.class,
                        TapePartition.LIBRARY_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public int getMinimumReadReservedDrives()
    {
        fetchBeanIfNull();
        return  m_bean.getMinimumReadReservedDrives();
    }


    synchronized public int getMinimumWriteReservedDrives()
    {
        fetchBeanIfNull();
        return  m_bean.getMinimumWriteReservedDrives();
    }


    synchronized public String getName()
    {
        fetchBeanIfNull();
        return  m_bean.getName();
    }


   synchronized public RetrieveBeansResult< TapeDrive > getTapeDrives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( TapeDrive.class ).retrieveAll(
            Require.beanPropertyEquals( TapeDrive.PARTITION_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< TapeDensityDirective > getTapeDensityDirectives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( TapeDensityDirective.class ).retrieveAll(
            Require.beanPropertyEquals( TapeDensityDirective.PARTITION_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< Tape > getTapes()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( Tape.class ).retrieveAll(
            Require.beanPropertyEquals( Tape.PARTITION_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< TapePartitionFailure > getTapePartitionFailures()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( TapePartitionFailure.class ).retrieveAll(
            Require.beanPropertyEquals( TapePartitionFailure.PARTITION_ID, m_bean.getId() ) );
    }


    synchronized public Quiesced getQuiesced()
    {
        fetchBeanIfNull();
        return  m_bean.getQuiesced();
    }


    synchronized public String getSerialNumber()
    {
        fetchBeanIfNull();
        return  m_bean.getSerialNumber();
    }


    synchronized public TapePartitionState getState()
    {
        fetchBeanIfNull();
        return  m_bean.getState();
    }


   synchronized public RetrieveBeansResult< StorageDomainMember > getStorageDomainMembers()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( StorageDomainMember.class ).retrieveAll(
            Require.beanPropertyEquals( StorageDomainMember.TAPE_PARTITION_ID, m_bean.getId() ) );
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( TapePartition.class ).attain( m_whereClause );
        }
    }


    synchronized public TapePartition unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private TapePartition m_bean;
}
