/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.tape.TapeFailure;
import com.spectralogic.s3.common.dao.domain.tape.TapeFailureType;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import java.util.Date;
import java.util.UUID;


public class TapeFailureRM
{
    public TapeFailureRM( TapeFailure bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public TapeFailureRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    TapeFailureRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public Date getDate()
    {
        fetchBeanIfNull();
        return  m_bean.getDate();
    }


    synchronized public String getErrorMessage()
    {
        fetchBeanIfNull();
        return  m_bean.getErrorMessage();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public TapeDriveRM getTapeDrive()
    {
        if ( null != m_bean )
        {
            return new TapeDriveRM( m_bean.getTapeDriveId(), m_serviceManager );
        }
        return new TapeDriveRM(
                Require.exists( TapeFailure.class,
                        TapeFailure.TAPE_DRIVE_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public TapeRM getTape()
    {
        if ( null != m_bean )
        {
            return new TapeRM( m_bean.getTapeId(), m_serviceManager );
        }
        return new TapeRM(
                Require.exists( TapeFailure.class,
                        TapeFailure.TAPE_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public TapeFailureType getType()
    {
        fetchBeanIfNull();
        return  m_bean.getType();
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( TapeFailure.class ).attain( m_whereClause );
        }
    }


    synchronized public TapeFailure unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private TapeFailure m_bean;
}
