/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.BlobStoreTaskPriority;
import com.spectralogic.s3.common.dao.domain.shared.Quiesced;
import com.spectralogic.s3.common.dao.domain.shared.ReservedTaskType;
import com.spectralogic.s3.common.dao.domain.tape.TapeDrive;
import com.spectralogic.s3.common.dao.domain.tape.TapeDriveState;
import com.spectralogic.s3.common.dao.domain.tape.TapeDriveType;
import com.spectralogic.s3.common.dao.domain.tape.TapeFailure;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import java.util.Date;
import java.util.UUID;


public class TapeDriveRM
{
    public TapeDriveRM( TapeDrive bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public TapeDriveRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    TapeDriveRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public boolean getCleaningRequired()
    {
        fetchBeanIfNull();
        return  m_bean.getCleaningRequired();
    }


    synchronized public String getErrorMessage()
    {
        fetchBeanIfNull();
        return  m_bean.getErrorMessage();
    }


    synchronized public boolean isForceTapeRemoval()
    {
        fetchBeanIfNull();
        return  m_bean.isForceTapeRemoval();
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public Date getLastCleaned()
    {
        fetchBeanIfNull();
        return  m_bean.getLastCleaned();
    }


    synchronized public Integer getMaxFailedTapes()
    {
        fetchBeanIfNull();
        return  m_bean.getMaxFailedTapes();
    }


    synchronized public String getMfgSerialNumber()
    {
        fetchBeanIfNull();
        return  m_bean.getMfgSerialNumber();
    }


    synchronized public BlobStoreTaskPriority getMinimumTaskPriority()
    {
        fetchBeanIfNull();
        return  m_bean.getMinimumTaskPriority();
    }


    synchronized public TapePartitionRM getPartition()
    {
        if ( null != m_bean )
        {
            return new TapePartitionRM( m_bean.getPartitionId(), m_serviceManager );
        }
        return new TapePartitionRM(
                Require.exists( TapeDrive.class,
                        TapeDrive.PARTITION_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public Quiesced getQuiesced()
    {
        fetchBeanIfNull();
        return  m_bean.getQuiesced();
    }


    synchronized public ReservedTaskType getReservedTaskType()
    {
        fetchBeanIfNull();
        return  m_bean.getReservedTaskType();
    }


    synchronized public String getSerialNumber()
    {
        fetchBeanIfNull();
        return  m_bean.getSerialNumber();
    }


    synchronized public TapeDriveState getState()
    {
        fetchBeanIfNull();
        return  m_bean.getState();
    }


   synchronized public RetrieveBeansResult< TapeFailure > getTapeFailures()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( TapeFailure.class ).retrieveAll(
            Require.beanPropertyEquals( TapeFailure.TAPE_DRIVE_ID, m_bean.getId() ) );
    }


    synchronized public TapeRM getTape()
    {
        if ( null != m_bean )
        {
            return new TapeRM( m_bean.getTapeId(), m_serviceManager );
        }
        return new TapeRM(
                Require.exists( TapeDrive.class,
                        TapeDrive.TAPE_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public TapeDriveType getType()
    {
        fetchBeanIfNull();
        return  m_bean.getType();
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( TapeDrive.class ).attain( m_whereClause );
        }
    }


    synchronized public TapeDrive unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private TapeDrive m_bean;
}
