/*******************************************************************************
 *
 * Copyright C 2021, Spectra Logic Corporation and/or its affiliates.
 * All rights reserved.
 *
 ******************************************************************************/

/*******************************************************************************
 *                    AUTO-GENERATED FILE - DO NOT MODIFY
 * This file is a relational model file. It is not generated by the normal build
 * process. In order to update this file to match the current DAO layer, please
 * run the main method of com.spectralogic.s3.common.dao.orm.util.ModelGenerator
 * directly from your IDE. This will regenerate ALL RM objects.
 ******************************************************************************/
package com.spectralogic.s3.common.dao.orm;

import com.spectralogic.s3.common.dao.domain.ds3.Bucket;
import com.spectralogic.s3.common.dao.domain.ds3.BucketAcl;
import com.spectralogic.s3.common.dao.domain.ds3.CanceledJob;
import com.spectralogic.s3.common.dao.domain.ds3.CompletedJob;
import com.spectralogic.s3.common.dao.domain.ds3.DataPolicyAcl;
import com.spectralogic.s3.common.dao.domain.ds3.GroupMember;
import com.spectralogic.s3.common.dao.domain.ds3.Job;
import com.spectralogic.s3.common.dao.domain.ds3.User;
import com.spectralogic.s3.common.dao.domain.ds3.UserIdObservable;
import com.spectralogic.s3.common.dao.domain.notification.AzureTargetFailureNotificationRegistration;
import com.spectralogic.s3.common.dao.domain.notification.BucketChangesNotificationRegistration;
import com.spectralogic.s3.common.dao.domain.notification.Ds3TargetFailureNotificationRegistration;
import com.spectralogic.s3.common.dao.domain.notification.GenericDaoNotificationRegistration;
import com.spectralogic.s3.common.dao.domain.notification.JobCompletedNotificationRegistration;
import com.spectralogic.s3.common.dao.domain.notification.JobCreatedNotificationRegistration;
import com.spectralogic.s3.common.dao.domain.notification.JobCreationFailedNotificationRegistration;
import com.spectralogic.s3.common.dao.domain.notification.PoolFailureNotificationRegistration;
import com.spectralogic.s3.common.dao.domain.notification.S3ObjectCachedNotificationRegistration;
import com.spectralogic.s3.common.dao.domain.notification.S3ObjectLostNotificationRegistration;
import com.spectralogic.s3.common.dao.domain.notification.S3ObjectPersistedNotificationRegistration;
import com.spectralogic.s3.common.dao.domain.notification.S3TargetFailureNotificationRegistration;
import com.spectralogic.s3.common.dao.domain.notification.StorageDomainFailureNotificationRegistration;
import com.spectralogic.s3.common.dao.domain.notification.SystemFailureNotificationRegistration;
import com.spectralogic.s3.common.dao.domain.notification.TapeFailureNotificationRegistration;
import com.spectralogic.s3.common.dao.domain.notification.TapePartitionFailureNotificationRegistration;
import com.spectralogic.s3.common.dao.domain.pool.ImportPoolDirective;
import com.spectralogic.s3.common.dao.domain.shared.ImportDirective;
import com.spectralogic.s3.common.dao.domain.tape.ImportTapeDirective;
import com.spectralogic.s3.common.dao.domain.tape.RawImportTapeDirective;
import com.spectralogic.s3.common.dao.domain.target.ImportAzureTargetDirective;
import com.spectralogic.s3.common.dao.domain.target.ImportS3TargetDirective;
import com.spectralogic.util.bean.lang.Identifiable;
import com.spectralogic.util.db.query.Require;
import com.spectralogic.util.db.query.WhereClause;
import com.spectralogic.util.db.service.api.BeansServiceManager;
import com.spectralogic.util.db.service.api.RetrieveBeansResult;
import java.util.UUID;


public class UserRM
{
    public UserRM( User bean, final BeansServiceManager serviceManager )
    {
        m_bean = bean;
        m_whereClause = null;
        m_serviceManager = serviceManager;
    }


    public UserRM( final UUID requiredId, final BeansServiceManager serviceManager )
    {
        this( Require.beanPropertyEquals( Identifiable.ID, requiredId ), serviceManager );
    }


    UserRM(final WhereClause whereClause, final BeansServiceManager serviceManager)
    {
        m_bean = null;
        m_whereClause = whereClause;
        m_serviceManager = serviceManager;
    }


    synchronized public String getAuthId()
    {
        fetchBeanIfNull();
        return  m_bean.getAuthId();
    }


    synchronized public DataPolicyRM getDefaultDataPolicy()
    {
        if ( null != m_bean )
        {
            return new DataPolicyRM( m_bean.getDefaultDataPolicyId(), m_serviceManager );
        }
        return new DataPolicyRM(
                Require.exists( User.class,
                        User.DEFAULT_DATA_POLICY_ID,
                        m_whereClause ),
                m_serviceManager );
    }


    synchronized public UUID getId()
    {
        fetchBeanIfNull();
        return  m_bean.getId();
    }


    synchronized public int getMaxBuckets()
    {
        fetchBeanIfNull();
        return  m_bean.getMaxBuckets();
    }


   synchronized public RetrieveBeansResult< GroupMember > getGroupMembers()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( GroupMember.class ).retrieveAll(
            Require.beanPropertyEquals( GroupMember.MEMBER_USER_ID, m_bean.getId() ) );
    }


    synchronized public String getName()
    {
        fetchBeanIfNull();
        return  m_bean.getName();
    }


    synchronized public String getSecretKey()
    {
        fetchBeanIfNull();
        return  m_bean.getSecretKey();
    }


   synchronized public RetrieveBeansResult< GenericDaoNotificationRegistration > getGenericDaoNotificationRegistrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( GenericDaoNotificationRegistration.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< JobCreatedNotificationRegistration > getJobCreatedNotificationRegistrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( JobCreatedNotificationRegistration.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< S3ObjectPersistedNotificationRegistration > getS3ObjectPersistedNotificationRegistrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( S3ObjectPersistedNotificationRegistration.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< ImportTapeDirective > getImportTapeDirectives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ImportTapeDirective.class ).retrieveAll(
            Require.beanPropertyEquals( ImportDirective.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< JobCreationFailedNotificationRegistration > getJobCreationFailedNotificationRegistrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( JobCreationFailedNotificationRegistration.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< RawImportTapeDirective > getRawImportTapeDirectives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( RawImportTapeDirective.class ).retrieveAll(
            Require.beanPropertyEquals( ImportDirective.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BucketAcl > getBucketAcls()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BucketAcl.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< S3ObjectLostNotificationRegistration > getS3ObjectLostNotificationRegistrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( S3ObjectLostNotificationRegistration.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< SystemFailureNotificationRegistration > getSystemFailureNotificationRegistrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( SystemFailureNotificationRegistration.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< Bucket > getBuckets()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( Bucket.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< TapePartitionFailureNotificationRegistration > getTapePartitionFailureNotificationRegistrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( TapePartitionFailureNotificationRegistration.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< DataPolicyAcl > getDataPolicyAcls()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( DataPolicyAcl.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< JobCompletedNotificationRegistration > getJobCompletedNotificationRegistrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( JobCompletedNotificationRegistration.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< AzureTargetFailureNotificationRegistration > getAzureTargetFailureNotificationRegistrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( AzureTargetFailureNotificationRegistration.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< TapeFailureNotificationRegistration > getTapeFailureNotificationRegistrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( TapeFailureNotificationRegistration.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< S3TargetFailureNotificationRegistration > getS3TargetFailureNotificationRegistrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( S3TargetFailureNotificationRegistration.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< ImportAzureTargetDirective > getImportAzureTargetDirectives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ImportAzureTargetDirective.class ).retrieveAll(
            Require.beanPropertyEquals( ImportDirective.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< Job > getJobs()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( Job.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< Ds3TargetFailureNotificationRegistration > getDs3TargetFailureNotificationRegistrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( Ds3TargetFailureNotificationRegistration.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< CanceledJob > getCanceledJobs()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( CanceledJob.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< StorageDomainFailureNotificationRegistration > getStorageDomainFailureNotificationRegistrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( StorageDomainFailureNotificationRegistration.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< BucketChangesNotificationRegistration > getBucketChangesNotificationRegistrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( BucketChangesNotificationRegistration.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< CompletedJob > getCompletedJobs()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( CompletedJob.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< S3ObjectCachedNotificationRegistration > getS3ObjectCachedNotificationRegistrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( S3ObjectCachedNotificationRegistration.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< PoolFailureNotificationRegistration > getPoolFailureNotificationRegistrations()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( PoolFailureNotificationRegistration.class ).retrieveAll(
            Require.beanPropertyEquals( UserIdObservable.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< ImportPoolDirective > getImportPoolDirectives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ImportPoolDirective.class ).retrieveAll(
            Require.beanPropertyEquals( ImportDirective.USER_ID, m_bean.getId() ) );
    }


   synchronized public RetrieveBeansResult< ImportS3TargetDirective > getImportS3TargetDirectives()
    {
        fetchBeanIfNull();
        return m_serviceManager.getRetriever( ImportS3TargetDirective.class ).retrieveAll(
            Require.beanPropertyEquals( ImportDirective.USER_ID, m_bean.getId() ) );
    }


    private void fetchBeanIfNull()
    {
        if ( null == m_bean )
        {
            m_bean = m_serviceManager.getRetriever( User.class ).attain( m_whereClause );
        }
    }


    synchronized public User unwrap()
    {
        fetchBeanIfNull();
        return m_bean;
    }

    //m_whereClause is ignored if m_bean != null
    private final WhereClause m_whereClause;
    private final BeansServiceManager m_serviceManager;
    private User m_bean;
}
