require 'logger'
require "active_record"
require "ostruct"
require "yaml"
require "erb"

# Most of this comes from
# activerecord/lib/active_record/railties/databases.rake.  That file is not
# imported/loaded and used directly since there are too many Rails references
# in it and this isn't a Rails app.
db_namespace = namespace :db do
  DBCONFIG = File.expand_path("../config/database.yml", __FILE__)
  MIGRATE_DIR = File.expand_path("../db/migrate", __FILE__)

  def current_config(options = {})
    return @current_config if @current_config
    @current_config = YAML::load(ERB.new(File.read(DBCONFIG)).result)
  end

  desc "Create the database from config/database.yml"
  task :create => :environment do
    create_database(current_config)
  end

  desc "Drop the database"
  task :drop => :environment do
    drop_database(current_config)
  end

  desc "Migrate the database through scripts in db/migrate.  Target specific " \
       "versions with VERSION=x"
  task :migrate => [:environment] do
    version = ENV["VERSION"]
    version = version.to_i unless version.nil?
    ActiveRecord::MigrationContext.new(MIGRATE_DIR, 
        ActiveRecord::SchemaMigration).migrate(version)
  end

  task :environment do
    ActiveRecord::Base.establish_connection(current_config)
    ActiveRecord::Base.schema_format = :sql
  end

  def create_database(config)
    @encoding = config['encoding'] || ENV['CHARSET'] || 'utf8'
    begin
      ActiveRecord::Base.establish_connection(config.merge('database' => 'postgres', 'schema_search_path' => 'public'))
      ActiveRecord::Base.connection.create_database(config['database'], config.merge('encoding' => @encoding))
      ActiveRecord::Base.establish_connection(config)
    rescue Exception => e
      if e.message !~ /^PG::DuplicateDatabase/
        $stderr.puts e, *(e.backtrace)
        $stderr.puts "Couldn't create database for #{config.inspect}"
      end
    end
  end

  def drop_database(config)
    ActiveRecord::Base.establish_connection(config.merge('database' => 'postgres', 'schema_search_path' => 'public'))
    ActiveRecord::Base.connection.drop_database config['database']
  end

  def set_psql_env(config)
    ENV['PGHOST']     = config['host']          if config['host']
    ENV['PGPORT']     = config['port'].to_s     if config['port']
    ENV['PGPASSWORD'] = config['password'].to_s if config['password']
    ENV['PGUSER']     = config['username'].to_s if config['username']
  end
end
